### ISSUE TITLE
"citation undefined" in Sublime Text 3

### ISSUE THREAD

**Issue by Vivianstats** [SublimeText/LaTeXTools#1024]
Hello,

I was using Sublime Text 2 on Windows and LaTexTools worked well with my .tex file. I just switched to Sublime Text 3 on Mac, and I'm having problems with the citations.

I got warning messages like
Package natbib Warning: Citation `conesa2016survey' on page 2 undefined on input line 106.
for all my citations. There were no errors except these warnings.

I checked the .bbl file and it's empty. I tried LaTexTools-check system, and everything listed is "available". I think there's nothing wrong with the .tex file since it worked with Sublime Text 2. 

Any hints on how to fix this? Thanks a lot!

**Comment by Vivianstats** [comment]
Updates:

I was using
\bibliographystyle{Chicago}

now I switched to
\bibliographystyle{apalike}
and I can get correct pdf file!

But what's wrong with "Chicago"?

**Comment by r-stein** [comment]
This question is related to miktex and texlive and not to LaTeXTools. You may better ask it at http://tex.stackexchange.com/.

**Comment by ig0774** [comment]
The problem is probably to do with case-sensitivity. The `chicago` bibstyle should be used with `\bibliographystyle{chicago}`.

**Comment by Vivianstats** [comment]
Thank you all very much! I was able to fix it by using `\bibliographystyle{chicago}`.

**Comment by faridcher** [comment]
I also had this problem with my custom `ecology.bst` style. I changed it to the built-in `natbib` auth-year style (i.e. `plainnat`) and the problem resolved. I have  a  few custom styles that I may use in future. Is there a workaround to this issue? ( I didn't experience this problem with TexStudio)

[ecology.bst](https://github.com/SublimeText/LaTeXTools/files/1308764/ecology.zip)

**Comment by ig0774** [comment]
@faridcher: It's really hard to guess what the issue might be with so little detail. LaTeXTools doesn't do anything that should stop you from using custom BSTs files, provided LaTeX and BibTeX can find them. The issue above was caused by a capital letter, that caused LaTeX to be unable to find the corresponding BST—independent of LaTeXTools. Without some details as to where you've put this custom BST file, what builder you're using, what sort of settings you've tweaked for the build, etc. it's pretty much impossible to guess.
