### ISSUE TITLE
How to set up 'standalone' for LaTeXTools on ubuntu

### ISSUE THREAD

**Issue by Erichliu00** [SublimeText/LaTeXTools#1027]
running 'check for system shows that I am missing standalone for preview:
However, I am not able to find how to correct this.  
I guess it may be included in LaTEX-extra but I am unwilling to install the whole LaTeX-extra since it is very big.

> standalone                     missing
> preview                        available
> xcolor                         available
> amsmath                        available
> amssymb                        available
> latexsym                       available
> mathtools                      available

**Comment by ig0774** [comment]
This is one good argument for using the vanilla TeXLive distribution rather than the version bundled with your Linux distribution. AFAIK, `tlmgr` is only available in vanilla TeXLive.

As I see it there are three options:

1. Uninstall your distro's TeXLive and install the vanilla version. A good guide on how to install vanilla TeXLive on Debian-based systems (incl. Ubuntu) is [here](http://tex.stackexchange.com/a/95373). If you're concerned about disk space, you should probably install just the `basic` profile. Any packages you're missing can then be installed using `sudo tlmgr install <package_name>`.

1. Manually download and install the package from CTAN. Instructions for manually installing a package can be found [here](http://tex.stackexchange.com/a/73017) as "Method 3".

1. If you're really adventurous, it may be possible to come up with a template that works without requiring the `standalone` package, perhaps by using the `preview` package directly. We provide the *advanced* setting `preview_math_template_file` which you can use to specify the absolute path of the template file to use instead of our default template. Obviously, we can only provide minimal support for this option, but if you want to pursue this line the default template looks like this:
 ```latex
\documentclass[preview,border=0.3pt]{standalone}
% import xcolor if available and not already present
\IfFileExists{xcolor.sty}{\usepackage{xcolor}}{}%
<<packages>>
<<preamble>>
\begin{document}
% set the foreground color
\IfFileExists{xcolor.sty}{<<set_color>>}{}%
<<content>>
\end{document}
```

**Comment by Erichliu00** [comment]
Thank you! I will have a try at using vanilla TeXLive distribution soon.
