### ISSUE TITLE
Support image preview with custom \graphicspath

### ISSUE THREAD

**Issue by lucainnocenti** [SublimeText/LaTeXTools#1037]
This is definitely closely related to #665, and less directly to #977.
However, no direct mention of this specific feature was made there, and it seems like something possibly easier to implement than those cases.

Is it possible to have the image previewer look into the paths specified in the preamble using `\graphicspath`?

To be more specific, consider the case in which we have somewhere in the preamble the line

    \graphicspath{{../figures/}}

and then in the text we have `\includegraphics{foo.png}`, where `foo.png` is in `../figures/foo.png`.

Can this be implemented? Or is it just as hard as the related issues above?

**Comment by r-stein** [comment]
If we support `\graphicspath` we should support it everywhere, so we should add it to the fill-all-helper, the image preview, and jump-to-anywhere (and maybe somewhere else).

We also need to change the document analysis to support the [`regex module`](https://github.com/facelessuser/sublime-regex) instead of the default `re`, because we need to have recursive regex to match nested braces. Currently we have problems to work internally with commands, that have braces inside the argument.

None of this is hard to implement and it is somewhere in the TODO list, but it is not completly trivial and requires some time. I don't know when we come to support `\graphicspath`, but unfortunatly I don't expect it to be added soon.

**Comment by musm** [comment]
+100 for this feature. I'm wondering for people working in reports do you really dump all your figures in the same folder as the main tex file?

**Comment by r-stein** [comment]
I usually write something like `\includegraphics{img/image_name.pdf}` and put all images in a folder with the name `img `.

**Comment by r-stein** [comment]
This has been added in `st3-4.0.0-alpha.0`, please enable [prereleases](https://github.com/SublimeText/LaTeXTools#prereleases) to use it.
