### ISSUE TITLE
Dictionaries package no longer in PackageControl

### ISSUE THREAD

**Issue by jdumas** [SublimeText/LaTeXTools#1042]
Hi,

The [Dictionaries](https://packagecontrol.io/packages/Dictionaries) package has apparently been removed from PackageControl. Do you have any idea why? There is no bug tracker on their github repository, so it's hard to ask. Since you recommend installing it on your README, I think maybe you could update your instructions to put a warning or something.

**Comment by r-stein** [comment]
I think that guy highly disliked the new version number system enforced by package control, so he removed all his packages (cant find the discussion at the moment).
Since we link to the github page and that package has an installation instruction, the current version is not wrong. However I agree that adding some kind of warning "This package is not in Package Control, you have to manually install it." may be better.

**Comment by jdumas** [comment]
Argh, if that's the case, that's a very childish reason. But well, Sublime being closed source to start with, we are not really in a position to complain.

**Comment by r-stein** [comment]
Package Control is open source (https://github.com/wbond/package_control). As far I know it will be updated automatically if you clone it from github with git.
You can also press *ctrl+shift+p* and select *Package Control: Add Repository* and insert the link https://github.com/titoBouzout/Dictionaries. After that you can install it as always.
Yeah that may be something to add to the readme.

**Comment by r-stein** [comment]
I have added it to the readme: https://github.com/SublimeText/LaTeXTools#spell-checking

**Comment by jdumas** [comment]
Ah, that's a nice feature! I didn't know it was possible to install packages that way. Glad I asked =)
