### ISSUE TITLE
Question: Synced Scrolling with Skim?

### ISSUE THREAD

**Issue by diego898** [SublimeText/LaTeXTools#1047]
I have sublime and skim take up halfs of my screen and frequently jump between them using the keyboard shorcuts and ctrl+clicking. 

I was wondering if its even possible to have a "synced scrolling" where scrolling in latex would attempt to have skim also scroll to the corresponding part in the pdf.

**Comment by r-stein** [comment]
Thats not possible and won't come soon. However you can add forward sync to a mousebinding, if you want to.

**Comment by diego898** [comment]
Thanks - do you know "where" its not possible? As in skim has no ability to scroll by an external output? Sublime has no ability to send an external signal based on mouse input? Both?

**Comment by r-stein** [comment]
The "not possible" was meant in a practical "it is not supported and I doubt it will be supported" not a "it is not possible at all", because I didn't have a closer look at that.
Especially interactions with pdf viewers are more complex, because they are platform depend and have to be implemented for each viewer. In addition I doubt that viewers have some API to trigger commands, when you change the viewport (scroll trough the document). In Sublime Text you somehow detect that, but changing the position in the pdf viewer sets to focus to the viewer for several viewers. So we have to steal the focus back, but your scrolling will stop each few seconds.

**Comment by diego898** [comment]
I see what you mean - it makes sense. Others get around this by having the text editing and displaying all in one built in app. 

Thanks! I consider this question answered and will close this issue!
