### ISSUE TITLE
Adding the List Scope to a new Environment

### ISSUE THREAD

**Issue by pravin-endeavour** [SublimeText/LaTeXTools#1170]
@r-stein 
When defining a new environment, how can you add it to the scope `meta.environment.list.itemize.latex`?
I want to do this, so that when I press `"Control + Enter"`, I can have the` \item` result on a new line.

MWE (in the preamble):

```
\newenvironment{test}{
    }%
    {%
}

```

**Comment by r-stein** [comment]
You can edit the file LaTeX/LaTeX.sublime-syntax via PackageResourceViewer. Then search for the itemize line https://github.com/sublimehq/Packages/blob/v3138/LaTeX/LaTeX.sublime-syntax#L390

and change it to this: (add `|test`)

```yaml
- match: '((\\)begin)(\{)\s*(itemize\*?|test)\s*(\})'
```

I am currently working on a feature to provide contexts for environments #1167 , so this should be easier in the future. Then you just need to add a keybinding instead of a changing the syntax file.

**Comment by pravin-endeavour** [comment]
Fantastic, that worked brilliantly!

**Comment by r-stein** [comment]
I have now added it to the PR, so you can check it out and add the keybinding:

``` js
    {
        "keys": ["ctrl+enter"], "command": "insert_snippet", "args": {"contents": "\n\\item $0"},
        "context":
            [
                { "key": "selector", "operand": "text.tex.latex"},
                { "key": "latextools.env_selector", "operand": "itemize, test"}
            ]
    },
```

It works like the normal scope selectors, but with environments.
