### ISSUE TITLE
Rest of the document grayed out if a command called `\comment` is used

### ISSUE THREAD

**Issue by lucainnocenti** [SublimeText/LaTeXTools#1176]
As per the title, see the following screenshot showing the problem:

![image 1](https://user-images.githubusercontent.com/10957113/28118817-89738956-670a-11e7-9476-dde513a38802.png)

It does not even matter if the document has a valid document structure. Just create a file with `.tex` or `.bib` extension and write something like `\comment` somewhere, and all the following text will be grayed out.
It does not happen if the file has another extension, like `.c`, so I assume it's a problem with LaTeXTools?

**Comment by r-stein** [comment]
The `\comment` command is provided by the package [`comment`](https://www.ctan.org/texarchive/macros/latex/contrib/comment). Since Sublime Text syntax are static the special commands are either included or not this won't change (unless the definition is somewhere wrong). You can either locally change the syntax definition or rename the command.

**Comment by lucainnocenti** [comment]
you mean to change the syntax definition in LaTeXTools I guess? Where should I change this?

**Comment by r-stein** [comment]
The syntax is provided by Sublime Text itself not by LaTeXTools. You can install Package Resource Viewer and open the file `LaTeX/LaTeX.sublime-syntax` with it. Afterwards delete [this line](https://github.com/sublimehq/Packages/blob/v3138/LaTeX/LaTeX.sublime-syntax#L777).

**Comment by lucainnocenti** [comment]
I didn't realise it it was syntax provided by Sublime Text itself. Thanks for the tip on how to change this option.
