### ISSUE TITLE
bib auto-complete breaks on new view into file with "No bib files found!"

### ISSUE THREAD

**Issue by joernhees** [SublimeText/LaTeXTools#1258]
to reproduce:
- open some _project_ with several latex documents
- add the `"settings": {"TEXroot": "main.tex"}` setting to the project's `.sublime-project` file
- open one of the child files and make sure `\cite{}` will pop up the bib auto-completion
- Open a new view of the same file `File / New View into File`
- try again: `\cite{}` in the new view, still works
- drag the new view out of the current sublime window to create a separate window
- try again: `\cite{}`

**Comment by ig0774** [comment]
Thanks for the detailed bug report. Unfortunately, I cannot reproduce the error you're describing. Could you maybe provide some more details about your setup? For example: Are you using a Sublime Text project or just a folder? Do the "child" files have a `%!TEX root` directive at the top or not?

**Comment by joernhees** [comment]
sorry i forgot to mention that... it's a project with a `"settings": {"TEXroot": "test.tex"}` setting. I made a minimal sample [here](https://github.com/SublimeText/LaTeXTools/files/1474944/test.zip). Notice that i didn't include the `.sublime-workspace`, so you might need to re-create the project.

Trying to reproduce the bug, i made a small [video](https://github.com/SublimeText/LaTeXTools/files/1474962/vids.zip) that sadly i can only share as .zip (yay, github).

I noticed that you actually need to "drag" the new view out of the current window for the bug to appear.

**Comment by ig0774** [comment]
Thanks so much for the detailed reply! If it involves dragging the view out of the window, I don’t think we can fix this. The problem is that ST associates projects with windows rather than with views, files, or workspaces so when you drag the tab into a new window, it loses its connection to the project settings and hence it loses the reference to the texroot.

(If you want to see this for yourself:

1. Open a LaTeX document normally
1. Open the console (**View -> Show Console**)
1. In the console enter `view.settings().get(“TEXroot”)` and press enter. You should see the value from your project settings file.
1. Open a new view into the file (you can actually get the same behaviour by dragging the existing tab to a new window)
1. In the console in the new window, enter `view.settings().get(“TEXroot”)` and press enter. No result will be returned.
1. Drag this tab back to the original window and run the command from the console again, the original value will be returned.

Unfortunately, since this is ST-level behaviour, I’m not sure we can fix it, at least not without creating behaviour that is both computationally expensive and breaks the way ST functions outside of LaTeXTools.

Now, as for how to accommodate having two windows open with a view to the same file (which is a useful setup!) I have a couple of suggestions. First, instead of dragging the new tab to a new window, you can create a new “group” using **View -> Groups -> New Group...** and instead drag the tab into the new group (which by default will appear on the right- hand side of the same view). This will allow to view two locations in the same file side-by-side without adding a new window, and so without losing the connection to the project. Alternatively, consider switching to using the `%!TEX root =` directives in your “child” files, which does not depend on then Sublime project mechanism.

Hope that helps. Let me know if you need further help!

**Comment by joernhees** [comment]
Yeah, the thing with the texroot comments is that they are sublime specific, and annoying for others. Thanks for the workaround idea though...

i'll close this, but hope that maybe ST will support multi window views of one project at some point ;)
