### ISSUE TITLE
When using autocomplete on \cite{}, no quick panel is triggered

### ISSUE THREAD

**Issue by ErikkT4** [SublimeText/LaTeXTools#1264]
Hi everyone,

when I use the autocomplete function (by pressing the Tab-Key on my keyboard) after typing "\c" so that it completes it to "\cite{keylist}", no quick panel is shown. However, when I don't use autocomplete but type the full "\cite{", die quick panel containing all the references from my .bib file does show up.

Is this on purpose? Is it a bug? Or am I just using the from configurations?

Any tip would be appreciated! Thanks!
Erik

**Comment by r-stein** [comment]
If use the autocompletion you can afterwards press *C-l, C-f* to open the cite (input/ref/...) quickpanel. In addition if you press *ctrl-space* to open the completion list it should be filled with the corresponding cite entries.
This is the expected behavior and we can't easily open the panel if you insert the autocomplete entry, because the API doesn't provide such an option (one could work around it, but I don't think that's a good idea).

**Comment by ErikkT4** [comment]
I see, thanks for the quick and comprehensive response! That exactly answered my question. :)
