### ISSUE TITLE
The order of the auto-complete list of \usepackage

### ISSUE THREAD

**Issue by Romeoly** [SublimeText/LaTeXTools#1271]
When I type `\usepackage{`, a list of available packages is popped up. And then as I type in the name of the package, unmatched packages will be filtered out. This is very useful. 

But  the name of the package could be very short. For example, there is a package providing bold math letters named `bm`, which is exactly two-letter long. If I type `\usepackage{` and then enter `bm`, the candindate `bm` is not in the first place. The first one is `beamercolorthemefibeamer-mu`. 

`bm` is the best-match, right? So, can the popped list be rearranged so that `bm` or so is in the first place?

**Comment by r-stein** [comment]
I am not sure whether the filtered out packages are in the same order as the suggestions. If so it would be easy to sort the package names by length.

**Comment by ig0774** [comment]
Unfortunately, just sorting the packages by length doesn't seem to resolve the issue.

The problem is that, for very short input strings, ST's fuzzy-matching algorithm favours matches at word boundaries over the exact match. Changing the sorting of packages by length results (on my machine) in `bidi-media9` being the top-ranked match, with `bm` still down below all results in the forms `b...-m...` and b...M...`. In other words, its pretty much the same as the current state, though the results within those sets are now sorted by length rather than alphabetically.

**Comment by Romeoly** [comment]
Is it possible to move a package which cannot match more inputs to the first place? I mean, just move the full-name-matching package (eg, the `bm` package) to the first place, leaving the order of others unchanged. 

This makes sure that a package will be inserted before or when its full name is typed.

**Comment by ig0774** [comment]
Short answer: without changes to the underlying fuzzy-match algorithm: no. ST plugins have no ability to change ordering in that way.

**Comment by Romeoly** [comment]
Thank you for your short answer which the the only thing I can understand :-)
