### ISSUE TITLE
fail to compile in Miktex on Mac

### ISSUE THREAD

**Issue by qiuzhu** [SublimeText/LaTeXTools#1285]
I install the new update MiKTeX app in Mac and just test:

```
TraditionalBuilder: Engine: pdflatex. Invoking latexmk... done.
This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".
```

and the tex environment is 👍 Variable  Value
```
--------  -----
PATH      /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Library/TeX/texbin:/Users/lotus/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin

Program      Location                   Status     Version
-------      --------                   ------     -------
latexmk      /Users/lotus/bin/latexmk   available  This application failed to start because it could not find or load the Qt platform plugin "cocoa"
pdflatex     /Users/lotus/bin/pdflatex  available  MiKTeX-pdfTeX 2.9.6607 (1.40.18) (MiKTeX 2.9.6600)
xelatex      /Users/lotus/bin/xelatex   available  MiKTeX-XeTeX 2.9.6609 (0.99999) (MiKTeX 2.9.6600)
lualatex     /Users/lotus/bin/lualatex  available  This is LuaTeX, Version 1.07.0 (MiKTeX 2.9.6600)
```

**Comment by ig0774** [comment]
Off-hand, it sounds like either an issue where MiKTeX didn’t install all the necessary QT4 libs or it installed them in a location that can’t be seen from the LaTeXTools environment. I’ve never tried MiKTeX on a Mac, so I can’t comment there.

The two obvious solutions would be to use MiKTeX to install latexmk (I think something like the command `mpm —install latexmk` would do it from the Terminal. Alternatively, try switching to the `basic` builder, which will likely work since the LaTeX executables themselves seem to be there.

**Comment by qiuzhu** [comment]
I install the `latexmk` using the Miktex , and  Now it works!
