### ISSUE TITLE
Word count instead of 'character' count

### ISSUE THREAD

**Issue by MOOnLyer** [SublimeText/LaTeXTools#1294]
In the status bar, it shows character instead of words. Is there a way to do the word counts instead?

**Comment by ig0774** [comment]
I don’t think it’s possible to override the status bar, but running the command `LaTeXTools: Word Count` will run [`texcount`](http://app.uio.no/ifi/texcount/), which is a program designed to count words in LaTeX documents. Note that because word counts in LaTeX is a very complex issue you may have to do some setup to your document to get accurate counts. See the [`texcount` documentation](http://app.uio.no/ifi/texcount/download.php?doc=TeXcount_3_1.pdf) for details.

**Comment by pkjmesra** [comment]
You could also use something like this package: http://eyalarubas.com/count-words-in-sublime-text-3.html
