### ISSUE TITLE
LaTeXTools in Visual Studio Code?

### ISSUE THREAD

**Issue by gkvallis** [SublimeText/LaTeXTools#1295]
This is not a feature request for Sublime Text, so this forum may not be the appropriate place to ask. But have you considered a port to Visual Studio Code (VS Code) from (yes) Microsoft? 
    The reason one might want it is that VS Code, which is open source, is a powerful editor, with active development and it is getting a lot of traction. Development of Sublime seems rather intermittent, although etter recently. I had hoped Atom to be a replacement but I find it too sluggish for daily use. There is a latex package on VS Code but it does not have the power or features of LaTeXTools (well, what does?).
   The reason the the port might be do-able is that VS Code is is similar to, and draws from, Sublime and Atom in a great many ways and some packages appear to have been directly ported. Indeed VS Code is sometimes called a speedy version of Atom. 
   I realise that it might still be quite a bit of work. I also realise this post is not about Sublime, so apologies if you find the request inappropriate.

**Comment by r-stein** [comment]
Currently the Atom package is way behind of the features from the Sublime Text version and I doubt that it would be better for vscode. Porting from Sublime Text requires to rewrite all code, because it is a different programming language and also tied to the Editor API. IMO the main advantage is to have an idea of the features and how they work.

Nonetheless I think the best creator for a vscode LaTeX package would be someone who uses LaTeX on vscode.
