### ISSUE TITLE
Can not Install Dictionaries Package

### ISSUE THREAD

**Issue by MOOnLyer** [SublimeText/LaTeXTools#1296]
Open the command palette (C-shift-p) and select the entry Package Control: Add Repository
Paste the url: https://github.com/titoBouzout/Dictionaries and press enter
Now you can install it as any other package: First select Package Control: Install Package in the command panel and afterwards select Dictionaries to install it

I followed the procedure above. After adding the repository, I can not find Dictionaries when I try to install via package control as I always do.

**Comment by r-stein** [comment]
This also doesn't work for me. It seems that something has been changed with package control. Alternatively you can download the repo as zip, unzip it and put it into the folder you open with *Preferences > Browse Packages...*

**Comment by shannonPrice** [comment]
Stop!!! Take me off your email now

**Comment by r-stein** [comment]
@shannonPrice unwatch this repository if you don't want to get notifications, but please don't spam under every issue

**Comment by ig0774** [comment]
This is probably caused by a wbond/package_control#1334. Basically, GitHub changed their API to reject requests using TLSv1, which is considered insecure. Unfortunately, Python 3.3 (the version used by ST3) doesn’t have a mechanism to specify using TLSv1.2 explicitly. PackageControl is working on fixing this, but haven’t yet released a beta version of the client with the fixed code. In other words, this’ll hopefully be solved in a future update.

@shannonPrice: you get these emails because you’re watching this repo on GitHub. Unwatch the repo and unsubscribe of any threads you’ve chimed in on and the emails should stop. Unfortunately, there’s no way we can do this for you.
