### ISSUE TITLE
build on file save / live preview possible?

### ISSUE THREAD

**Issue by marconett** [SublimeText/LaTeXTools#1327]
please excuse my ignorance, but does this package support building pdfs on file save and instantly previewing the changes in the pdf viewer using forward sync?

i consulted the docs, settings, etc. couldn't find a thing about this.

**Comment by r-stein** [comment]
Since building pdfs can be a long procedure and forward sync requires to leave sublime text for a few seconds, we decided not to support building on save. Especially in combination with auto save this can be quite problematic.
If you want to build when you press ctrl+s you can just change the ctrl+s keybinding for latex files. If you really want to build on every save I think there is an other package for that, but I do not recommend that for LaTeX files.

**Comment by marconett** [comment]
What I do with latex (simple 1-2 page letters / invoices) usually compiles in about a second, so I might try the keybinding workaround.

Thank you for taking the time to explain this!
