### ISSUE TITLE
cwl completio: limited number of cwls

### ISSUE THREAD

**Issue by hadisfr** [SublimeText/LaTeXTools#1346]
The cwl repo referenced in documentations, [LaTeX-cwl](https://github.com/LaTeXing/LaTeX-cwl), support limited number of packages. Also, it seems inactive for more than two years.
Due to importance of cwl support, I think it worths create a new repo for cwls and do some improvements in codes to be compatible with texstudio's cwls, or , at least, update documentations and add some other links.
E.g. in addition to https://github.com/LaTeXing/LaTeX-cwl, there are some cwls available at:
* https://github.com/texstudio-org/texstudio (official TexStudio's repo)
* https://github.com/hubutui/texstudio-cwl
* https://github.com/hadisfr/LaTeX-cwl (my fork of LaTeX-cwl, including some of above cwls and cwl for bidi and xepersian packages)

**Comment by r-stein** [comment]
I have also observed that the creator of LaTEXing is not active anymore. Taking a package is in general possible and a good idea if he doesn't merge  PRs.
You would start with creating an issue at the original package informing him that you are looking forward to take the package because he is inactive.

**Comment by hadisfr** [comment]
https://github.com/LaTeXing/LaTeX-cwl is updated now!
