### ISSUE TITLE
cite author complition bug

### ISSUE THREAD

**Issue by hadisfr** [SublimeText/LaTeXTools#1361]
`\cite` complition shows `????` for multi-line bibitem `author` attribute in bib file.
```biblatex
@Article{borle18,
author="Borle, Neil C.
and Feghhi, Meysam
and Stroulia, Eleni
and Greiner, Russell
and Hindle, Abram",
…
```
![image](https://user-images.githubusercontent.com/24562441/44471043-5476f500-a640-11e8-8759-fbb1f1042a97.png)

**Comment by hadisfr** [comment]
Also, it fails to render first name of author in `misc` types; e.g.:
```bibtex
@misc{code:safari18:pybiclique,
  title = {pybiclique},
  author = {Hadi Safari},
  howpublished = {\url{https://github.com/hadisfr/pybiclique}}
}
```
![image](https://user-images.githubusercontent.com/24562441/44512077-acf4d380-a6ce-11e8-8f0e-62356ebe3b3e.png)

**Comment by ig0774** [comment]
The second one is the expected behaviour, i.e., the default format is:

```{author_short} {year} - {title_short} ({keyword})```

Where ```{author_short}``` is either 1) the last name of a single-author piece, 2) the last names of both authors conjoined with an `&` for a two-author piece, or 3) the last name of the first author with "et. al." for a multiple author piece. You can change the format in your sublime settings to something like:

```{author} {year} - {title_short} ({keyword})```

which will give you everything in the name field, though this may cause the year, title and keyword to not be displayed.

**Comment by ig0774** [comment]
The first problem can be fixed by changing the `bibliography` setting to `"new"`. The difference between the two bibliographies is that the "new" bibliography reader uses a proper parser, so it handles cases like this, but as a result it can perform worse that the "traditional" bibliography reader that uses regexes, but has some pretty fixed formatting requirements and doesn't support multiline values.

**Comment by ig0774** [comment]
Note that you may have to completely delete the LaTeXTools cache to see the results.

**Comment by hadisfr** [comment]
Thank you. For the second one, I expected first name. For the second one, I didn't know limitations of traditional parser. It may be a good idea to add what you have said in https://github.com/SublimeText/LaTeXTools/issues/1361#issuecomment-415465560 to [docs](https://latextools.readthedocs.io/en/latest/settings/#bibliographic-references-settings). 🤔 

Besides, when do you think version 4 will be out? There are many pending pull requests.
