### ISSUE TITLE
How to add `--max-print-line=10000` to Tex Live (Linux Only)?

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/LaTeXTools#1404]
Miktex on Windows accepts `--max-print-line=10000``, but on Linux with Tex Live, this parameter is not supported.

On `builder_settins` I can add this:
```js
	"builder_settings" : {
		"display_log" : false,
		"options" : ["-file-line-error", "-halt-on-error", "--max-print-line=10000"],
```

But it will also be set to Linux.

It does not work if I set this inside the https://latextools.readthedocs.io/en/latest/settings/#platform-specific-settings:
```js
		"options" : ["-file-line-error", "-halt-on-error"],

		"osx" : {
		},

		"windows" : {
			"options" : ["-file-line-error", "-halt-on-error", "--max-print-line=10000"],
		},

		"linux" : {
		}

```

**Comment by ig0774** [comment]
Platform-specific settings are only for very specific settings and don't override other settings.

A few years ago, I submitted #633, which would've allowed this kind of thing, but because of the complexity it would add to troubleshooting user issues, it was ultimately rejected and withdrawn, and so there's currently no way to do what you are requesting short of using the script builder, where settings can be set on a per-OS basis.

In general using `-file-line-error`  is probably a bad idea with LaTeXTools as it will almost certainly break log file parsing. Also, I don't know that `-halt-on-error` does anything productive.
