### ISSUE TITLE
Autocomplete not Working

### ISSUE THREAD

**Issue by xXQWERTXx** [SublimeText/LaTeXTools#1432]
LaTeX-cwl is installed and `env_auto_trigger: true`, but there is no autocomplete for autocompleting `\begin{}` and `\end{}`. 
Tried toggling with `C-l,t,a,e`.
Tried adding
```
{   
    "keys": ["{"],
    "context":  [
        { "key": "setting.disable_latex_ref_cite_auto_trigger", "operator": "not_equal", "operand": true },
        { "key": "selector", "operator": "equal", "operand": "text.tex.latex - comment" },
        { "key": "selection_empty", "operator": "equal", "operand": true, "match_all": true },
        { "key": "lt_fill_all_env.open_curly", "operator": "equal", "operand": true, "match_all": true },
        { "key": "selector", "operator": "equal", "operand": "text.tex.latex" }
    ],
    "command": "latex_fill_all", 
    "args": {
        "completion_type": "env", 
        "insert_char": "{"
    }
},
```
to user keybinds as suggested by #1429.
Not sure what else to do.

**Comment by xXQWERTXx** [comment]
Just to clarify, the issue isn't that there is no autocomplete when typing `\begin{`.
It's that there is no autocomplete when typing `\beg` or some variant, then hitting tab to get the autocomplete for `\begin{} and \end{}` (with 2 cursors, one in each curly bracket pair).
As a side note, why does the autocomplete show up as a command menu, as opposed to the one that appears on `\` alone?

**Comment by r-stein** [comment]
Have you tried to restart sublime text? The installation of LaTeX-cwl is only checked during startup. Otherwise please open the ST console ``ctrl+` `` and check for the output when it should be triggered.

**Comment by xXQWERTXx** [comment]
Multiple times. Output shows that `latex_cwl` has been loaded. `\b` triggers the autocomplete menu. `\begin` + `{` triggers the autocomplete command panel. `\b` + `tab` to autocomplete into `\begin{` and `\end{` does nothing still.

**Comment by r-stein** [comment]
@xXQWERTXx Ah now I understand your issue. It is a general limitation, that we can't hook into the autocompletion. There we can't open the fill all helper, when you use the autocompletion to insert `\begin{` via autocompletion.
However the fill-all completions are also inserted into the autocomplete menu, therefore you can use the environment from there (note that you need to prefix `\ ` for that completion type).
E.g.
![insert_be](https://user-images.githubusercontent.com/12573621/65062630-b6597980-d97c-11e9-87b8-9ec624248b52.gif)


Otherwise you may press `C-l, C-f` to manually trigger the fill-all helper.

**Comment by xXQWERTXx** [comment]
Oh! I see
Thank you very much for your help @r-stein.
