### ISSUE TITLE
msg.exe has stop working-preview_math

### ISSUE THREAD

**Issue by phatsp** [SublimeText/LaTeXTools#1469]
Hi, I'm learning LaTeX on SublimeText3. I have LaTeX Tools and LaTeXYZ installed. The auto pdf preview of LaTeXYZ works fine under the math/ equation environment. Then I want some customization for my math (text-align in equation) which I found [here ](https://tex.stackexchange.com/questions/1665/how-can-i-add-left-aligned-text-to-an-equation). But the pdf-preview threw an error like this.
 Does anyone know how to solve this problem?

*I know it would be more appropriate to post this question on LaTeXYZ, but their git somehow doesn't have many people visiting.
![image](https://user-images.githubusercontent.com/43247670/76440231-1e4ec100-63f0-11ea-80fe-1796d44a759c.png)

**Comment by r-stein** [comment]
It seems that there is an issue with the ghostscript conversation of the pdf (step 3 below).

The process of the math preview is the following:
1. generate a tex file based on the current math equation
2. create a pdf for the tex file with `pdflatex` (or the configured program)
3. use ghostscript to convert the pdf to a png
4. show the png in Sublime Text

It does not seem to be a general problem, because it works for me:

![image](https://user-images.githubusercontent.com/12573621/76537323-e68e5a80-647d-11ea-8511-d7188b5209ce.png)

Does the preview work in general and fails on this specific equation or doesn't it work at all?

**Comment by phatsp** [comment]
Yes, It works normally for the usual math environment $ $, but fails with this specific case, when put under` {flalign*}` environment.

**Comment by phatsp** [comment]
I  looked into other issues and found the latest answer `"preview_math_hires": false` #1430 helps . Thank you @r-stein. Closing the topic.
