### ISSUE TITLE
New Window Opened on Build

### ISSUE THREAD

**Issue by adam-blakey** [SublimeText/LaTeXTools#1530]
I'm on Sublime Text 4113 on Windows 10. 

Previously, after I've built my .tex file, the PDF viewer would become the active window and then it would switch back to ST being the active window. However, as of today, after building an entirely new window pops up in ST.

I've noticed with ST 4113 there's an entry "Windows: Always make a new window when launching main executable on Windows". With this release being released today I'm not sure if this is an ST or LaTeXTools issue.

I'd like for the previous behaviour to be restored, where the window I am working on becomes the active window after building.

**Comment by sekti** [comment]
For me the following fix worked:
- Go into the LaTeX Tools settings (Preferences → Package Settings → LaTeXTools → Settings – User)
- Find the setting "windows" → "sublime_exectuable" and set it to "subl.exe"

The problem seems to be caused by the jump_to_pdf command with enabled keep_focus. LaTeXTools tries to give back focus to sublime by running sublime_executable after keep_focus_delay seconds have expired. If the setting sublime_executable is left blank, then sublime_text.exe is used as a default. As of version 4113, subl.exe should be used a a default instead.

**Comment by JustAdamHere** [comment]
That did the trick. Many thanks!

**Comment by deathaxe** [comment]
Fixed for Windows by v4
