### ISSUE TITLE
Code folding

### ISSUE THREAD

**Issue by consideRatio** [SublimeText/LaTeXTools#179]
Id like to get the ability to fold \sections and \subsections

**Comment by mpvharmelen** [comment]
+1

**Comment by msiniscalchi** [comment]
Support is coming. I already have patches, so please be patient.

**Comment by xacid** [comment]
Great! Thank you, msiniscalchi!

BTW, is it possible to have nested section folding? It seems now those folding with \begin{xxx} ... \end{xxx} are defined in Latex.tmLanguage using "foldingStartMarker". However, this rule folds to the nearest marker, but it is better to fold everything between the matching begin-end environment when we have nested environments in Latex. For example, a nested list should fold the whole list. Currently, only lines between two adjacent \begin are folded as follows. Note that if the nested list was indented correctly, then the folding would be nested as expected.

```
\begin{itemize}
[...]
\begin{itemize}
\item ...
\end{itemize}
\item ...
\end{itemize}
```

I have read this issue, and it seems nested folding is currently not supported by ST itself.
http://sublimetext.userecho.com/topic/116459-code-folding-support-for-nested-folds/
I know nested folding is a different issue (compared to section folding), but they are related because we usually expect to fold a \section to the next \section or \subsection (but not the next \{sub}paragraph or \begin). In fact, I rarely need to fold nested \begins, and thus I am satisfied with current non-nested \begin folding. However, I would really want to fold nested sections and paragraphs.

Please kindly consider this nested case. Thanks you!

**Comment by Gabriel-p** [comment]
+1

**Comment by GeekMe93** [comment]
+1, thank you!

**Comment by m-sostero** [comment]
+1
If at all possible, it would be nice if code folding worked by environment and didn't require indentation.
In LaTeX text can be nested within multiple environments (especially in Beamer within `\begin{frame} ... \end{frame}`); indentation is impractical as it takes precious screen estate.
It could be useful to be able to fold every nested environment without indentation:
```latex
┌─ ▼║\begin{itemize}
│   ║\item outer item
│┌─▼║\begin{enumerate}
││  ║\item inner item
│└─ ║\end{enumerate}
└── ║\end{itemize}

```
(Where `║` is the gutter boundary and `▼` is the code folding mark)

**Comment by r-stein** [comment]
@m-sostero If you use ST3 and [BracketHighlighter](https://packagecontrol.io/packages/BracketHighlighter) you have a command to fold the bracket content. It supports nested brackets and LaTeX environments. Hence you could use it to fold environments.
Though I don't know how to add the gutter folding marks.

PS.: The indendation based marks are integrated into ST itself.

**Comment by Gabriel-p** [comment]
That is a nice package, but since `\sections{}` have no closing statement, they can't be folded.

**Comment by r-stein** [comment]
@Gabriel-p Yes the answer was only for environments.

However in general I don't think many users will benefit from a folding without fold markers, because they would not know about the possibility to do it.

**Comment by m-sostero** [comment]
@r-stein Thanks. I tried [BracketHighlighter](https://packagecontrol.io/packages/BracketHighlighter): it's useful because it highlights the boundaries of the current environment with very bright tags in the gutter, but it doesn't seem to allow to fold the environment.
For that, you really need to intent the environment content, which – as you pointed out – seems built pretty deep into ST. I was wondering if LaTeXTools could address that for LaTeX files.
NB: The `▼` folding marks don't need to be always visible in the gutter to be useful: the default setting for all languages is that the mark appears only when you hover the mouse in the gutter at the beginning of the environment.

**Comment by r-stein** [comment]
@m-sostero If have the environments highlighted, press `ctrl+shift+p` and write `BracketHighlighter: Fold Bracket Content`. This will fold the bracket content. If you want a keybinding for that:

``` js
{
    "keys": ["alt+f"],
    "command": "bh_async_key",
    "args": {
        "plugin": {
            "command": "bh_modules.foldbracket",
            "type": ["__all__"]
        }
    },
},
```

As I said it does not add gutter marks and your comment strengthens my assumption, that it would be hard to use for the most users without them. The visibility is (as far I know) anyway controlled by the theme.

**Comment by m-sostero** [comment]
@r-stein thanks.
As I said, I get that `BracketHighlighter` supports folding from the environment tag (with a command or custom keybinding).
But this is arguably _less visible_ than implementing the gutter folding mark without requiring indentation: users expect ▼ to be there because it's the code-folding convention used in other languages (indeed, the mark appears when the code within the environment is indented).
But if the indentation requirement is built in too deep into ST3, you are right that it may not be worth the hassle.

**Comment by consideRatio** [comment]
I figure this is stale, I'm closing this.

**Comment by juanfal** [comment]
After some tinkering, I've built a plugin (saved in `~/Library/Application Support/Sublime Text/Packages/User/TeXfoldsect.py`) that folds the current section or the whole document leaving as title of each folded area the section/chapter name. It's quite useful as it presents an outline of your document:

    import sublime, sublime_plugin, subprocess

    # https://github.com/SublimeText/LaTeXTools/issues/179
    # ,{ "keys": ["super+alt+ctrl+left"], "command": "texfoldsect", "args": {"arg": ""},
    #     "context":
    #     [
    #         { "key": "selector", "operator": "equal", "operand": "text.tex.latex" }
    #     ]
    # }
    # ,{ "keys": ["super+shift+alt+ctrl+left"], "command": "texfoldsect", "args": {"arg": "all"},
    #     "context":
    #     [
    #         { "key": "selector", "operator": "equal", "operand": "text.tex.latex" }
    #     ]
    # }

    class texfoldsectCommand(sublime_plugin.TextCommand):
        def run(self, edit, arg):
            view = self.view
            self.pattern = r'\n^\\(sub)*(section\*?|chapter\*?){.*$' # ([^}]+)}'
            self.tam = view.size()
            self.cnt = 0
            if arg != 'all':
                self.fold()
            else:
                view.sel().clear()
                view.sel().add(sublime.Region(0, 0))
                while self.fold():
                    pass
            sublime.status_message(f"TOTAL folded sects/chaps: {self.cnt}")

        def fold(self):
            view = self.view
            r0 = view.find(self.pattern, view.sel()[0].begin(), flags=sublime.REVERSE)
            r1 = view.find(self.pattern, view.sel()[0].end())

            if r0.begin() == -1:
                start = 0
            else:
                start = r0.end()
            if r1.end() == -1:
                end = self.tam
            else:
                end = r1.begin()
            # if r.a == -1:
            #     sublime.status_message(f"No {arg} section/chapter")
            #     # subprocess.call(["say", "-v",  "Alex", f"No {arg} section/chapter"])
            #     # subprocess.call(["afplay", '/System/Library/Sounds/Tink.aiff'])
            # else:
            view.sel().clear()
            self.view.fold(sublime.Region(start, end))
            self.cnt += 1
            view.sel().add(sublime.Region(end+3, end+3))
            view.show_at_center(end+3)
            return r1.end() != -1

**Comment by odapg** [comment]
Hi @juanfal 
Thanks! for this, this is quite nice! Maybe you could make a repo out of it?
I would also have two suggestions should you want to develop this a little bit more: to fold the whole section when the caret is located in a section before its first subsection, and to fold Beamer's frames as well.
