### ISSUE TITLE
Configuring Adobe Acrobat Reader for view PDF files 

### ISSUE THREAD

**Issue by udaykadaboina** [SublimeText/LaTeXTools#45]
I have built a TeX file with ST2, but after I built the TeX file I get a prompt saying that 'Cannot launch Viewer, Make sure its in your PATH'. So I have put my Adobe Acrobat Reader in the path variable like this.'C:\Program Files (x86)\Adobe\Reader 10.0\Reader\AcroRD32.exe' but still I get the same error. Are there any clear steps to do this with AdobeAcrobat Reader rather than Sumatra PDF?

**Comment by clsmt** [comment]
What if I don't care about inverse and forward search? Why stripping the users of their ability to customize pdf viewer?

**Comment by r-stein** [comment]
This issue is more than five years old and now you can configure any pdf viewer you want with the [command viewer](https://latextools.readthedocs.io/en/latest/available-viewers/#command-viewer), but you may run into other issues using acrobat reader.

The reason to add the support for a single viewer (and expand it stepwise for more viewers) and not a configurable template for every viewer was IMO to provide a clean and easy path to edit LaTeX and have a better support for this specific viewer (e.g. the way how Sublime Text keeps focused after you compile is different based on the supported features of the viewer and the OS).

**Comment by clsmt** [comment]
@r-stein Yep I figured that out later. Thanks for the reply.
For viewer, choose "command", then in the options just write down the path to acrobat, or any other viewer.
By the way, I tried sumatraPDF before. the reason I stick with acrobat, is because it is the best rendering out there. It uses sub-pixel anti-aliasing. As far as I know, no other viewer implements that (is it patented?) But anyway this is a whole other conversation.
