### ISSUE TITLE
Unable to build since latexmk Update

### ISSUE THREAD

**Issue by norbert6** [SublimeText/LaTeXTools#467]
I just updated the latexmk-Package from 4.39 to 4.41.
But it seems like something changed, the Command Results are:

    Latexmk: This is Latexmk, John Collins, 1 January 2015, version: 4.41.
    : No such file or directory at c:/Tools/texlive/2014/texmf-dist/scripts/latexmk/latexmk.pl line 1810.
    C:\Tools\texlive\2014\bin\win32\runscript.tlu:652: command failed with exit code 2:
    perl.exe c:/Tools/texlive/2014/texmf-dist/scripts/latexmk/latexmk.pl -cd -e "$pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 %S %O'" -f -pdf B2.tex

unfortunately, I'm pretty new to this whole Latex stuff, can someone please help me to fix this?

**Comment by msiniscalchi** [comment]
Oh, no... that's beyond LaTeXTools' control, I am afraid. The latexmk
script gets invoked correctly. Can you check what happens if you run the
latexmk command from the command line? That is, open CMD.EXE, go to the
directory where your file is located, and give the following command:

latexmk -cd -e "$pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1
%S %O'" -f -pdf B2.tex

**Comment by norbert6** [comment]
The output ist the same as in Sublime Text...
looking at the code of the file, this is the part around line 1810:

    # Initially $aux_dir and $out_dir are either absolute or relative to CURRENT
    #    directory.
    # If we'll cd to directory of TeX file to do our work, we'll need to convert
    #   any relative directories to absolute, to preserve the user-requested
    #   directories after a cd.
    # Otherwise, we need to normalize them in our standard way (to ensure
    #   standardization in the places we use them.
    
    
    foreach ($out_dir, $aux_dir) {
        if ($do_cd) {
    	    $_ = abs_path( $_ );
        }
        else {
            # Remove aliases to cwd:
            $_ = normalize_filename( $_ );
            if ($_ eq '.' ) { $_ = ''; }
        }
    }


In the old version it is like this:

    foreach ($out_dir, $aux_dir) {
       # Remove aliases to cwd:
       $_ = normalize_filename( $_ );
       if ($_ eq '.' ) { $_ = ''; }
    }

I also found the following comment in the beginning of the file, not sure if related to this problem:

    # Re -cd issue !!!!!!!!!!!!! SEE "??!!" COMMENTS.
    #     If relative path is given for $out_dir or $aux_dir, and -cd is
    #     used, should it be interpreted w.r.t. initial cwd (i.e., cwd when
    #     latexmk is started), or w.r.t. to document directory???????
    # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by msiniscalchi** [comment]
OK, so sadly it's not a LaTeXTools issue but a latexmk bug (on Windows at
least). As a temporary patch, you could remove the -cd switch and instead
pass the full pathname to your file; if you want to try that, you can edit
the LaTeXTools settings file (in the Packages/User directory) and change
the builder option called "command." You need to remove the "-cd", but the
part I don't remember now is how to pass the full path instead of the base
file name---it's in the Sublime Text docs and I can't check right now,
sorry.

As a quick fix though, try using the "simple" builder. It does not use
latexmk at all, so it should run with no problems. However, if you have a
complex build, it may fail. (If you only use pdflatex and bibtex, you
should be fine).

On Mon, Jan 12, 2015 at 5:23 PM, norbert6 <notifications@github.com> wrote:

> The output ist the same as in Sublime Text...
> looking at the code of the file, this is the part around line 1810:
>
> # Initially $aux_dir and $out_dir are either absolute or relative to CURRENT
> #    directory.
> # If we'll cd to directory of TeX file to do our work, we'll need to convert
> #   any relative directories to absolute, to preserve the user-requested
> #   directories after a cd.
> # Otherwise, we need to normalize them in our standard way (to ensure
> #   standardization in the places we use them.
>
>
> foreach ($out_dir, $aux_dir) {
>     if ($do_cd) {
>         $_ = abs_path( $_ );
>     }
>     else {
>         # Remove aliases to cwd:
>         $_ = normalize_filename( $_ );
>         if ($_ eq '.' ) { $_ = ''; }
>     }
> }
>
> In the old version it is like this:
>
> foreach ($out_dir, $aux_dir) {
>    # Remove aliases to cwd:
>    $_ = normalize_filename( $_ );
>    if ($_ eq '.' ) { $_ = ''; }
> }
>
> I also found the following comment in the beginning of the file, not sure
> if related to this problem:
>
> # Re -cd issue !!!!!!!!!!!!! SEE "??!!" COMMENTS.
> #     If relative path is given for $out_dir or $aux_dir, and -cd is
> #     used, should it be interpreted w.r.t. initial cwd (i.e., cwd when
> #     latexmk is started), or w.r.t. to document directory???????
> # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/467#issuecomment-69667319>
> .
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661

**Comment by norbert6** [comment]
Thank you very much for your help.
I decided to roll back to version 4.39 for now, I just wanted to make sure it's not a change in the latexmk command syntax, which would affect all upcoming versions as well.
btw, it seems like there is already a fix for this, a new version 4.42 is listed here: http://www.ctan.org/pkg/latexmk

So I guess this Issue is fixed :)
