### ISSUE TITLE
Log parsing errors, does not properly detect compilation errors

### ISSUE THREAD

**Issue by jtanderson** [SublimeText/LaTeXTools#477]
I have a file in which there are various warnings, but still compiles on most systems. However, if serious errors occur in the file below the locations where these warnings are created, LaTeXTools does not correctly find them in the log file and report it.  You can see the console output from the build command and log file [here](https://gist.github.com/jtanderson/0888e7f19c529c8bc437). The important lines (where I've artificially introduced errors into the .tex file are 680 and 685 of paper.log. As you can see, the console output reports No Errors.

**Comment by allenh1** [comment]
Affects me as well.

**Comment by msiniscalchi** [comment]
Hmm... I tried creating the same errors (a double subscript, followed by an undefined command) but LaTeXTools picked both errors up just fine.... can you provide more info and possibly a minimal tex test file?

**Comment by msiniscalchi** [comment]
Hmm... I tried creating the same errors (a double subscript, followed by an undefined command) but LaTeXTools picked both errors up just fine.... can you provide more info and possibly a minimal tex test file?

**Comment by ig0774** [comment]
How you fix this is beyond me, but maybe someone more clever than I am can figure it out. Here's what I've worked out from @jtanderson's log sample: the problem isn't that the log parser wouldn't pick up those errors, it's that the parser stops at line 515 rather than continuing to the point in the log where those errors occur.

The culprit seems to be these two "lines":

                              {lem:equivariance}pdfTeX warning (ext4): destination w
    ith the same identifier (name{theorem.8}) has been already used, duplicate igno
    red
(506-508)

                             {lem:equivariance}pdfTeX warning (ext4): destination w
    ith the same identifier (name{theorem.9}) has been already used, duplicate igno
    red
(513-515)

These make it to the `file_useless_match` check in the `parseTeXlog.py` script where `file_useless1_rx` turns them into `) has been already used, duplicate ignored` and then restarts from the beginning. This string in turn reaches the check on line 477 which notes that it "denotes end of processing for current file." Unfortunately, the first time this is encountered (on line 508 of the log) the only file left is the main file (paper.tex) so the second time this happens (on line 515 of the log), it gets thrown into the `else` block on line 485 of the script, which prints an error and stops processing.
