### ISSUE TITLE
Image editing feature request

### ISSUE THREAD

**Issue by renatyv** [SublimeText/LaTeXTools#497]
My TeX documents contain multiple images (\includegraphics[width=0.8\linewidth]{images/non-linear-tfs.pdf}).
It would be nice to have the following features
1)image file name autocompletion
2)open-image-in-editor feature (from PDF viewer or sublime)

Current workflow is as follows:
1)Jump from PDF file to the source file by cmd+click
2)remember the image file name(path)
3)open the Image editor(Adobe Illustrator)
4)Open the file in the image editor

**Comment by ig0774** [comment]
Assuming you're on ST3, you may be able to reduce some of your workflow via the [SideBarEnhancements](https://github.com/titoBouzout/SideBarEnhancements), since you can customise the menu to launch Illustrator with the file selected in ST. You'd obviously still need to be in Sublime and actually open a folder (or project) rather than just a file for this to work, but maybe it saves  you a couple of steps...

**Comment by r-stein** [comment]
This has been implemented and can be closed.
The open image program can be defined in the `open_image_command` as described in the readme and default settings (you might want to remigrate your settings). The key binding is `ctrl-l ctrl-o` while being on the `\includegraphics`-command.
