### ISSUE TITLE
kpsewhich.py fails to call kpsewhich on OSX

### ISSUE THREAD

**Issue by aleth** [SublimeText/LaTeXTools#498]
Unfortunately, the new "also look in the texmf tree" feature is broken on OSX, because in kpsewhich.py, `Popen(['kpsewhich', filename], stdout=PIPE, stdin=PIPE)` fails to find kpsewhich and throws an OSError.
This is despite the same kpsewhich command line working properly when tried in a shell.

I attempted to fix this by adding "shell=True" to Popen, but when one does that, kpsewhich seems to be found but its output is not captured correctly (you always get an empty string).

Hardcoding the absolute path of kpsewhich in kpsewhich.py does work, but is an ugly workaround.

**Comment by aleth** [comment]
@ig0774, any ideas?

**Comment by ig0774** [comment]
Initially I was confused about this since I originally developed the feature on OSX, but I forgot that OSX uses a very sparse path for GUI apps which of course affects SublimeText. I recall seeing somewhere in the source tree something that adds a user-configured setting to the path. I'll look at integrating that...

**Comment by aleth** [comment]
Maybe reusing some of the code LatexTools uses to find pdflatex et al would work?

**Comment by msiniscalchi** [comment]
Take a look in the fillall-fold branch, file latex_installed_packages.py.
On OS X, you need to inject the PATH from the settings. Luckily it's the
same PATH used by tex & friends.


On Sun, Apr 26, 2015 at 8:57 AM, aleth <notifications@github.com> wrote:

> Maybe reusing some of the code LatexTools uses to find pdflatex et al
> would work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/498#issuecomment-96385761>
> .
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661

**Comment by ig0774** [comment]
Alright, this sent me a bit down the rabbit-hole, but I've tested it on Windows using SublimeText3 and Mac OSX using SublimeText3 and SublimeText2 without having kpsewhich on the default PATH. Basically #500 should resolve the issue.

@msiniscalchi: Have a look at what I did to call kpsewhich. When I tried copying the logic directly from the latex_installed_packages.py, I ran into some issues as modifying os.environ['PATH'] clobbers the PATH for SublimeText, so several other plugins I run started failing (the default settings for Windows have the texpath set to '', so effectively the PATH was being changed to ''). The way I've set this up seems to work by only modifying the local environment for the subprocess rather than for SublimeText.

**Comment by msiniscalchi** [comment]
Thank you. Just a comment though---the code in latex_installed_packages.py
is taken from makePDF.py, which (I assume) works fine. In makePDF.py, as
soon as the command is executed, the old path is restored; I assume that
latex_installed_packages.py does the same, and that, if kpsewhich also does
that, everything should be fine. But, I may be wrong.

On Tue, Apr 28, 2015 at 2:51 PM, ig0774 <notifications@github.com> wrote:

> Alright, this sent me a bit down the rabbit-hole, but I've tested it on
> Windows using SublimeText3 and Mac OSX using SublimeText3 and SublimeText2
> without having kpsewhich on the default PATH. Basically #500
> <https://github.com/SublimeText/LaTeXTools/pull/500> should resolve the
> issue.
>
> @msiniscalchi <https://github.com/msiniscalchi>: Have a look at what I
> did to call kpsewhich. When I tried copying the logic directly from the
> latex_installed_packages.py, I ran into some issues as modifying
> os.environ['PATH'] clobbers the PATH for SublimeText, so several other
> plugins I run started failing (the default settings for Windows have the
> texpath set to '', so effectively the PATH was being changed to ''). The
> way I've set this up seems to work by only modifying the local environment
> for the subprocess rather than for SublimeText.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/498#issuecomment-97185633>
> .
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661
