### ISSUE TITLE
Problem with TEXroot directive and .bib files autocomplete

### ISSUE THREAD

**Issue by odarriba** [SublimeText/LaTeXTools#515]
Hello!

I'm using ST3 (I don't really know if the issue is because of this or not), latest version of LaTeXTools and latest version of Git plugin (https://github.com/kemayo/sublime-text-git).

I've found that, when using TEXroot directive in project file to set the main file to compile in the project, and and adding a Git repository (so the Git plugin recognise it):
- LaTeXTools stops recognising this directive (and compiles the file you're editing only)
- `.bib` files aren't read and shows the annoying error message every time you make a `\cite{}`.

When you delete the repository files (`.gitignore` file and `.git` folder in my case) everything works again.

I don't really know if this issue is related to LaTeXTools or Git plugin (or even ST3), but I'd like to notify it in case someone want to look at it (I'm currently writing my final project's report, so I don't have time at the moment).

Kind regards,
odarriba

**Comment by ig0774** [comment]
Sounds weird... I can't reproduce that here. Do you have any project-specific settings for the git plugin? (Don't normally use that myself) What output is there on the console (ctrl + `) when you try to compile or `cite{}` an entry?

**Comment by odarriba** [comment]
My project settings are this:
```
{
	"folders":
	[
		{
			"file_include_patterns":
			[
				"*.tex",
				"*.bib"
			],
			"path": "."
		}
	],
	"settings":
	{
		"TEXroot": "TFGManual.tex"
	}
}
```

And I did the following from the console
```
cd TFG/Docs/TFGManual
git init
git add .
git commit -m "Initial commit."
```

Then I open the project using ST 3 (Build 3083), compiled the main file and opened another .tex in the same project. When I wrote `\cite{` the alert message appeared anthe console shown:

```
TEX root: '/Users/odarriba/TFG/Docs/TFGManual/contents/resultados/sections/resultados-host.tex'
Searching file: '/Users/odarriba/TFG/Docs/TFGManual/contents/resultados/sections/resultados-host.tex'
Bib files found: 
[]
error: No bib files found!
```

The plugins I'm using are: 
* Git v2015.02.06.06.00.56
* LaTeXTools v2015.04.13.03.23.00

And if I delete all the repository (`rm-rf .git*`) all returns back to normal...

**Comment by msiniscalchi** [comment]
Does the problem persist? If not, please close.

**Comment by ig0774** [comment]
Looking back at this, I'm wondering if it isn't related to #152 and the Git stuff is a bit of a red-herring...

**Comment by msiniscalchi** [comment]
I just tested this on Windows / ST3 and indeed I can reproduce it, in the following sense. 

* If I add a `\bibliography{...}` command in the root file but do **not** save it, then indeed the bibliography will not be picked up by LaTeXTools---I get the error message.
* If however I **save** the root file after adding the `\bibliography{}` command, then cite completion works as expected: the popup menu is shown, both when adding `\cite`s in the root file and in any included files.

So as @ig0774 suspected, Git has nothing to do with it---I have no Git projects in the directory I'm using for testing. The issue seems to be that, when a root file is specified, the citation completion code loads it from disk, without checking whether there is a fresher unsaved version in another view. Not sure this is worth fixing though, as the workaround is simply to save the master file as needed. (It's worth documenting though).

**Comment by odarriba** [comment]
Hi!

Finally, I haven't used Git and the problem disappeared. I don't know if this continues happening actually, because I have finished months ago the paper I was doing.

I hope this issue will be solved soon. You (and your package) really rocks when working with SublimeText.

**Comment by ig0774** [comment]
I'm assuming this is solved as its been about a year.
