### ISSUE TITLE
cite autocomplete doesn't work (MacTeX)

### ISSUE THREAD

**Issue by nickriches** [SublimeText/LaTeXTools#551]
Hi. I'm using MacTeX with my .bib folder stored in texmf. The document, including citations compiles fine, so latextools is obviously finding the .bib document. However, the cite autocomplete is not working. I get an error message "bib files not found!"

MWE below.

Thanks...

\documentclass{article}

\usepackage[backend=bibtex]{biblatex}
\addbibresource{bib.bib} % or
% \addbibresource{<database>.<extension>}

\begin{document}

\cite{van_der_lely_wh-movement_2003}

\cite{spencer_motion_2000}

\printbibliography

\end{document}

**Comment by nickriches** [comment]
Okay, I've made some progress. The autocomplete works if the .bib file is pasted into the folder where the tex file is. However, it doesn't work with the symlink I have set up in texmf/bibtex/bib/local/. It's a symlink to a folder called "bibliography" containing a number of .bib files. Perhaps I need to avoid folders within folders, or link to the the .bib file itself. Hopefully a solution is close...

**Comment by ig0774** [comment]
So you are most likely suffering from the same problem as #498, which was an error I made in writing the `kpsewhich` functionality that searches the TEXMF tree. This change has been fixed in #500, which has yet to be pulled into master, but hopefully will be included when the next release is made.

For now, you have a couple options:

1. Replace your `kpsewhich.py` with [the version from #500](https://raw.githubusercontent.com/ig0774/LaTeXTools/kpsewhich_bibfiles/kpsewhich.py). You can find `kpsewhich.py` by running the **Preferences: Browse Packages** command and opening the `LaTeXTools` folder.

1. If you add a symlink to the *file* itself in the same directory as your `tex` document it will work (LaTeXTools will not search subfolders; it searches for the path given in your `\addbibresource{}` command).

Last thing: LaTeXTools does nothing special for compilation. It merely calls a standard TeX tool-chain (normally `latexmk`, but it depends on how your builder is configured), so the fact that the file *compiles* says nothing about what LaTeXTools itself knows.

**Comment by nickriches** [comment]
Thanks - that's brill. Will have a go!

Nick

**Comment by nickriches** [comment]
Fantastic - works a treat!

Nick
