### ISSUE TITLE
Deleting temp files breaks Git tree

### ISSUE THREAD

**Issue by alexeyza** [SublimeText/LaTeXTools#552]
I've been using this plugin for a long time, no issues previously.
I can compile fine, but when using `CTRL + L, Backspace`, (which deletes temp files), somehow it breaks the Git tree... I get the following error `fatal: unable to read tree 0e43048ee11....` when trying to use `git status`

If I don't delete temporary files, everything works fine.

This issue started happening to me around 2 weeks ago. Tried cloning the repository from scratch and it happens again. Also other repositories have the same issue.

I'm using Ubuntu 15.04, Sublime Text 3 (build 3083), and current version of LatexTools.

**Comment by ig0774** [comment]
This is, unfortunately, a known issue that's addressed by #491 or, alternatively, #520. You can apply the changes from either of those pull requests to your local copy to fix the issue for now.

**Comment by alexeyza** [comment]
OK, thanks!
I used #520 to fix my issue. I hope this fix gets integrated to the master build.

**Comment by RomeshA** [comment]
@msiniscalchi This is a serious issue for many uses, so it would be great if #491 or #520 could please be merged ASAP. I created #491 almost 6 months ago, so this has been a very long time for a bug that causes data loss to remain unaddressed

**Comment by lucasnanni** [comment]
Unfortunately, when I first proposed the recursive deletion I didn't realized how unsafe would be inadvertently deleting all project files ending with those extensions. I think I have not tested it enough.. 

Although both #491 #520 have already addressed this issue, I would like to suggest (and discuss) something simpler: extensions like .idx, .bbl, blg, .brf, .synctex.gz, ... are usually associated with the main tex file. Based on my experience with LaTeX projects, I've seen only the .aux extension being associated with other filenames. 

Would it be safe to delete only the files that match: 'main.(idx|bbl|blg ...)' or 'anything.aux'? Would it also be enough?

**Comment by ig0774** [comment]
Well, one exception to that list is from #493, which generates a file in the form: `mainNotes.bib`.

It is probably safer to try to delete only files prefixed with the main file name than just indiscriminately deleting files with certain extensions as we do now. Even better, instead of recursing to delete everything, we could walk through the LaTeX document, find any files `\include`d (since that seems to be where we end up with a different `aux` file) and just delete those named files (I've occasionally had several separate documents in the same folder—not the best organisation, but a real possibility).

A couple of other suggestions that might be even cleaner, but more of a pain in the ass to implement: (1) if LaTeXTools properly supported `-aux-files` and / or `-output-direct` could we remove the need for recursion altogether? E.g., on non-MiKTeX we could dump the aux files to a folder, copy the pdf to the main folder and then just delete the output folder; MiKTeX would be simpler: just trash the `aux-files` directory. I suppose this would rely on forcing people to actually use the feature though. (2) At least when using the TraditionalBuilder, LaTeXTools could try to take advantage of the `.fdb_latexmk` file or perhaps even just delegate the cleaning to `latexmk` and then remove the `.fdb_latexmk` file. More generally, could we make the cleaning of the generated files something implemented by the builder?

**Comment by RomeshA** [comment]
Yes, I would think that the appropriate place for this would be the builder, since it's possible that the temporary files generated could depend on the builder. However, in the meantime can we just apply one of the existing fixes, at least temporarily? It would have to be better than just leaving corruption of user repositories unfixed

**Comment by joernhees** [comment]
woah... this just caught me and i accidentally broke the git repo for my PhD with this... can i suggest to do the following:

1. somehow fix this *as fast as possible*
2. then think about this can be done right?

the current version is really dangerously broken and make people rely on backups!

**Comment by r-stein** [comment]
I don't know why I am mentioned, but I agree that it would be nice to pull https://github.com/SublimeText/LaTeXTools/pull/520.

If you have problems and urgently need the pull request, you can manually checkout the branch with the pull request before the merge:

Open your shell in
- Windows: `%APPDATA%\Sublime Text 3\Packages\`
- OS X: `~/Library/Application Support/Sublime Text 3/Packages/`
- Linux: `~/.config/sublime-text-3/Packages/`

remove the LaTeXTools folder and then checkout the branch with the pull request

`git clone https://github.com/ig0774/LaTeXTools -b user_configurable_delete_files`

**Comment by alimuldal** [comment]
I also just broke the repo for my PhD thesis because of this - fortunately I had just pushed to remote, otherwise I would have lost a day's work. Not cool!

I totally agree with joernhees that this needs to be fixed in master as a matter of urgency - I guarantee that someone is going to get badly bitten by this bug.

**Comment by r-stein** [comment]
can be closed, fixed in https://github.com/SublimeText/LaTeXTools/pull/520

**Comment by joernhees** [comment]
:+1: thanks
