### ISSUE TITLE
Inserting using LaTeXTools causes Vintage/Vintageous to change mode

### ISSUE THREAD

**Issue by KamphuisAlex** [SublimeText/LaTeXTools#562]
When using autocomplete function provided by LaTeXTools, such as when inserting \autoref{fig....} and then selecting the label to refer to switches the vintage (or vintageous) package to normal mode.

I don't know how fixable this is, since it applies to another package. Nevertheless I'd like to hear your opinions.

**Comment by ig0774** [comment]
I don't use Vintage or Vintageous (for simplicity, I'll stick with calling both of them "Vintage") myself, but this behaviour may be addressable, if you're willing to do a little digging. Here are some details related to the functioning of LaTeXTools.

It would be good to clarify which autocomplete functionality this is breaking on. For both citations and refs, we hook into Sublime's completion list *and* provide our own via a quick panel (which looks similar to the command palette and generally pops up when you enter `{` in the appropriate location).

If this behaviour happens when the completion list is displayed, there's really nothing we can do. The text insertion from there is handled by ST itself and it would be up to the maintainers of Vintage to make that work correctly.

If its via the quick panel, LaTeXTools has more control over what happens. Essentially, when an item is selected in the quick panel, we run the `View.replace()` API method to insert the appropriate text and then run a small chunk of code to update the cursor position, which involves changing the current selection.

Again, here if its the call to the `View.replace()` bit that causes Vintage to enter normal mode, I'm not sure what we can do (other than not inserting the text), though it may be possible to come up with a hack to call whatever Vintage command needs to be called to restore Vintage to the appropriate mode. If it's the code that changes the cursor position (by updating the current selection) that causes the Vintage change in mode, we could try to make that code optional somehow.

The `replace` function is called in the command `latex_tools_replace` in `latex_ref_cite_completions`. The cursor moving code looks like this:

```python
caret = view.sel()[0].b
view.sel().subtract(view.sel()[0])
view.sel().add(sublime.Region(caret, caret))
```

And can be found in `latex_cite_completions`, `latex_input_completions` and `latex_ref_completions` in the LaTeXTools folder.

I am, however, a bit stuck on how we could do this in such a way that LaTeXTools remains agnostic about the existence and operation of Vintage. One option might be to use the upcoming plugin feature (#618) to provide some extensibility at the appropriate points in the code, but it may be some time before we get the plugin system fully integrated and can make this change.

Short of that, is there anyway that Vintage / Vintageous can be configured to deal with either of these functions (we certainly can't be the only package using them)?

**Comment by KamphuisAlex** [comment]
You are right in that LaTeXTools should have to be aware of other installed packages. Following that line of argument it can also not change behaviour of other packages, meaning that the 'bug' I described can not actually come from LaTeXtools. It is either that SublimeText resets some variables but more probable the Vintageous package does not handle the insertions by SublimeText correctly.

Thanks for your thoughts.
