### ISSUE TITLE
deleting temp files on OS X deletes all ps files in folder

### ISSUE THREAD

**Issue by moiraine-sedai** [SublimeText/LaTeXTools#575]
Steps to reproduce:

1. create latex file 'foo.tex'
2. make some file called, for example 's1.ps' and 's2.ps'. There do not need to be references to the ps in the latex code, and you may use 'touch s1.ps' and 'touch s2.ps' to create them as empty files.
3. invoke clear temp file from sublime text 3
4. s1.ps and s2.ps are deleted

Expected behavior: for ps files, delete foo.ps (base ps filename == base latex filename), but s1.ps and s2.ps should not be removed.

I do not have access to linux and windows, can someone verify if the issue is OS X only? This issue seems serious.

**Comment by moiraine-sedai** [comment]
Adding 
print("deleted: "+file_name_to_del)
after
os.remove(file_name_to_del)

shows the script removing the ps file.

**Comment by ig0774** [comment]
Currently, this *is* the expected behaviour, though I do agree it's potentially harmful. The "Delete Temporary Files" command clears *any* file that matches any extension it is configured to delete. 
 
There's some similar discussion of possible solutions in [#552](https://github.com/SublimeText/LaTeXTools/issues/552#issuecomment-148265232), which is related to this issue.

**Comment by msiniscalchi** [comment]
This is now configurable: I merged #520 which allows the user to configure what gets deleted. Closing.
