### ISSUE TITLE
Forward search not working on Windows

### ISSUE THREAD

**Issue by schmimae** [SublimeText/LaTeXTools#625]
Hey,

for some time the forward search has not been working using ST3 and Sumatra. Sumatra had been added to $PATH, but LaTeXTools could not find it:

Ctrl+l, j: 
__________________________________________
Traceback (most recent call last):
  File "H:\Program Files\Sublime Text 3\sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "C:\Users\Mike\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\jumpToPDF.py", line 228, in run
    subprocess.Popen(startCommands, startupinfo = si)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
Backup saved to: C:/Users/Mike/AppData/Roaming/Sublime Text 3/Backup/AutoBackups/2015-12-13/I/SugarSync/Documents/Miscellaneous/Finances/Aktien/Chapter/Boerse_213237.tex
True False True
!TEX root =  'I:\\SugarSync\\Documents\\Miscellaneous\\Finances\\Aktien\\Mitschrift.tex'
Jump to:  360 263
Windows, Calling Sumatra
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\Program Files\Sublime Text 3\sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "C:\Users\Mike\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\jumpToPDF.py", line 228, in run
    subprocess.Popen(startCommands, startupinfo = si)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
__________________________________________

A fix was to change jumpToPDF.py, line 220:

From
```
su_binary = prefs_win.get("sumatra", "SumatraPDF.exe") or 'SumatraPDF.exe'
```
to
```
su_binary = prefs_win.get("sumatra", "H:\Program Files (x86)\SumatraPDF\SumatraPDF.exe") or 'SumatraPDF.exe'
```

Apparently there is some issue with the $PATH var, because it works when using e.g. cmd and entering "SumatraPDF.exe".

Now Ctrl+l,j had been working and it opened Sumatra. However, forward sync was still not working. When opening Sumatra, it showed a small toast message stating that it could not find C:\Users\...\Sublime\...\abc.tex. Apparently it was looking in Sublime's folder for the .tex file, probably due to the modification above.

Therefore I changed jumpToPDF.py, line 224:
From
```
startCommands.append(srcfile)
```
to
```
startCommands.append(self.view.file_name())
```

and since then it has been working without a problem.

A similar workaround had to be done for viewPDF.py, line 51:
From
```
viewercmd = ["SumatraPDF.exe", "-reuse-instance"]
```
to
```
viewercmd = ["H:\Program Files (x86)\SumatraPDF\SumatraPDF.exe", "-reuse-instance"]
```

in order to allow Ctrl+l,v to work.

Before it failed with
__________________________________________
['SumatraPDF.exe', '-reuse-instance', 'I:\\SugarSync\\Documents\\Miscellaneous\\Mitschrift.pdf']
error: Cannot launch Viewer. Make sure it is on your PATH.
__________________________________________

**Of course, these are not fixes, but rather very dirty workarounds due to my limited knowledge.** I hope this will help you finding the real issue behind. By the way, I am using %!TEX root = .... statements.

Michael

**Comment by ig0774** [comment]
This is a long response. I apologise. TL; DR: use the `"sumatra"` setting; try disabling the autobackups plugin.

Finding Sumatra
-----

To prevent you from needing to apply such hacks, we already supply a setting which does this, at least for the forward sync command, namely the `"sumatra"` setting (which is what the line you modified in `jumpToPDF.py` is trying to load). You can control this setting by going to the `"windows"` section of `LaTeXTools.sublime-settings` (which itself can be found in **Preferences** -> **Package Settings** -> **LaTeXTools** -> **Settings - User**; if that file does not yet exist, please run the **LaTeXTools: Reconfigure and migrate settings** command from the command pallette.

The `"windows"` block should look like this:

```
"windows": {
		// Path used when invoking tex & friends; "" is fine for MiKTeX
		// For TeXlive 2011 (or other years) use
		// "texpath" : "C:\\texlive\\2011\\bin\\win32;$PATH",
		"texpath" : "",
		// TeX distro: "miktex" or "texlive"
		"distro" : "miktex",
		// Command to invoke Sumatra. If blank, "SumatraPDF.exe" is used (it has to be on your PATH)
		"sumatra": "",
		// Command to invoke Sublime Text. Used if the keep_focus toggle is true.
		// If blank, "subl.exe" or "sublime_text.exe" will be used.
		"sublime_executable": "",
		// how long (in seconds) to wait after the jump_to_pdf command completes
		// before switching focus back to Sublime Text. This may need to be
		// adjusted depending on your machine and configuration.
		"keep_focus_delay": 0.5
	},
```

You want to change the line to says `"sumatra": ""` to `"sumatra": "H:\\Program Files (x86)\\SumatraPDF\\SumatraPDF.exe"`.

We do need to adjust the viewer command to take account of that setting (so ctrl-l, v works as expected), and I'll try to get that fix into the next release. Thanks for pointing this out.

----

Forward Sync
-----

Regarding the forward sync issue, I can't really tell what's going on, but I have a suspicion that it has something to do with being in a subfile in a subdirectory of the main file, since we *only* pass in the base file name (e.g. `abc.tex`) rather than, e.g., `Chapter\Boerse_213237.tex`. Is the path that you wrote as `C:\Users...\Sublime...\abc.tex` in fact `C:\Users...\Sublime Text 3\Packages\abc.tex`? And is `abc.tex` not in the same folder as your root file?

In any case, this is definitely something we need to patch, its just a matter of figuring out how it is best to do that. (I'm concerned about ensuring we can still support scenarios like spaces or non-ASCII characters in the file path and that we can produce something that works on all platforms).

**Comment by schmimae** [comment]
ig0774, thank you for the fast response - and for all the work regarding LaTeXTools, it is awesome!

# Finding Sumatra
You are absolutely right, using the new `sumatra` setting works. My setting file was too old and did not have this specific setting, yet. I stumbled upon it yesterday but did not have the time to update my initial post - long story short: It works. Thank you.

# Forward Sync
I am **pretty** sure that the path has been C:\Users\x\AppData\Roaming\Sublime Text 3\..\abc.tex. However, unfortunately I cannot reproduce this anymore, because now Sumatra tries to access H:\Program Files\Sublime Text 3\abc.tex instead (Sublime Text's installation folder), which is still wrong. Maybe it has to do with some changes I did yesterday to the settings file. The correct folder would be e.g. C.\Users\x\Desktop\abc.tex. The attempted path is the same whether I use the master file (C.\Users\x\Desktop\abc.tex) or a sub file (C.\Users\x\Desktop\Chapter\chap1.tex) which references the master file. It works when using `startCommands.append(self.view.file_name())`.

**Comment by r-stein** [comment]
For forwards sync this code
```py
rootPath, _ = os.path.split(root)
srcfile = os.path.relpath(self.view.file_name(), rootPath)
```
seems to give the same result if its in the same folder (non-ASCII paths), but also works for files in subfolders. Though I didn't tried it on other platforms.

**Comment by msiniscalchi** [comment]
I just checked. Indeed this seems to be a Windows-only issue. I'm pushing a bugfix now.

**Comment by msiniscalchi** [comment]
OK, it should work now (after considerable stupidity on my part). Can someone please test and, if OK, close?

Unfortunately we need different handling for Sumatra and Skim. Skim wants the root source file; Sumatra wants the included source file. Ah, well!

**Comment by schmimae** [comment]
Confirmed on my end, thank all three of you!

**Comment by ig0774** [comment]
@msiniscalchi: I'm not sure this is actually isn't a platform-specific issue. Let me explain...

Given the following project structure:

```
----main_file.tex
  |---- subfolder/
      |----included_file.tex
```

where `main_file` has these contents:

```latex
\documentclass{article}
\usepackage{lipsum}
\begin{document}
\lipsum[1-50] % several pages of text
\include{subfolder/included_file}
\lipsum[52-100] % lots more text
```

and `included_file` is (for example) just this:

```latex
%!TEX root = ../main_file.tex
\lipsum[51]
```

Invoking `C-l, j` in `included_file.tex` opens Skim, etc. but does not jump to the correct location, which is the behaviour @schmimae described originally.

Prior to c573f70, when calling the viewer, LaTeXTools only passes the basename of the file that that the view command was run from (in my example above, `included_file.tex`). This works fine if the tex file is in the same folder as the pdf file, but fails when it isn't. The change of c573f70 passes this file name a path relative to the root TeX document (which is also the relative path to the PDF), so, again in terms of my example, Sumatra now gets `subfolder\included_file.tex` as the file in question. And that, I think, needs to get passed to any viewer.

Changing line 195 to `srcfile = os.path.relpath(self.view.file_name(), os.path.split(root)[0])` seems to resolve this issue on my Mac and be harmless otherwise. But I'm concerned that I've missed something or misunderstood something here, so I haven't yet committed this.

**Comment by msiniscalchi** [comment]
@ig0774 I shouldn't be allowed to code, or at least test :) I think you're right. I tested on Windows by including a file in a subdirectory... but on Mac somehow I forgot, and included a file in the current directory!  So yes, I think your fix should work.
