### ISSUE TITLE
Forward search no longer working with Skim?

### ISSUE THREAD

**Issue by alanmillard** [SublimeText/LaTeXTools#631]
As of a few days ago, forward search seems to have stopped working with Skim. I didn't change any of my configuration files, so could this have been broken by a recent update?

When I try to forward search, the PDF refreshes but the position doesn't change. Strangely, reverse search still works.

I've checked that forward_sync is set to true in LaTeXTools.sublime-settings. I also tried "Reconfigure LaTeXTools and migrate settings", but it didn't seem to make any difference.

I'm using:

LaTeXTools v3.6.0
Skim version 1.4.16 (90)
Mac OS X El Capitan version 10.11.2 (15C50)

**Comment by ig0774** [comment]
Certainly the changes for v3.6.0 involved reworking the forward sync code, but not in a way that should have made it completely unworkable on OS X. Almost none of the changes touched the Skim-related code and, FWIW, it's been working on my machine.

We did have a recent report (#625) of a failure with forward sync in multifile documents that does affect OS X. Could that possibly be what's going on here? (In this scenario, everything would've worked until you were trying to jump to a location in an `\include`d or `\input`ed file; this will be fixed in the next release).

Otherwise, could you try running forward sync and report anything that gets printed to the Sublime console?

**Comment by alanmillard** [comment]
@ig0774: Thanks for the prompt reply. I've just read your comments in #625, and this does appear to be the same problem. I was trying to jump to a location in an `\include`d file that's in a subdirectory. Everything works fine if I attempt to forward-search in the root tex file.

Glad to hear this will be fixed in the next release!

**Comment by arahlin** [comment]
Forward sync seems to work fine for me with Skim as long as the file paths are absolute instead of relative.  That is, I replace line 195 in jumpToPDF.py with

    srcfile = self.view.file_name()

instead of a path relative to `root`.  Is there a particular reason to require a relative path here in the code?  It seems like you want a path relative to CWD anyway, but why bother if the full path to the file is already known?

**Comment by ig0774** [comment]
@arahlin: Thanks. You're absolutely right and I've updated the `master` to reflect this.

**Comment by ig0774** [comment]
Alright since, the new release is now available, I'm closing this.
