### ISSUE TITLE
Prevent wrapping after backslashes

### ISSUE THREAD

**Issue by xsanda** [SublimeText/LaTeXTools#643]
Is it possible to prevent wordwrap from splitting a backslash from its command name?
![image](https://cloud.githubusercontent.com/assets/8607022/12374818/09fe16b6-bca0-11e5-8142-862a23e43c6c.png)

**Comment by arahlin** [comment]
The combination of [Auto Wrap](https://github.com/randy3k/AutoWrap) and [Sublime Wrap Plus](https://github.com/ehuss/Sublime-Wrap-Plus) packages will do what you want.  However, this will insert hard wraps (line breaks) instead of the default soft line wrapping.  I personally like this behavior, especially for longer paragraphs.

I haven't looked into how to do this correctly for the soft wraps...

**Comment by ig0774** [comment]
See [this forum discussion](https://forum.sublimetext.com/t/word-wrapping-in-latex-files-st-st2/1403), especially jps's comments. It can be done, but would require modifying the LaTeX syntax file (which this plugin currently doesn't do).

**Comment by PeterPablo** [comment]
It might be worth to check, whether this behavior changes, after https://github.com/sublimehq/Packages/pull/370 is pulled.

**Comment by ig0774** [comment]
I'm closing this since its fundamentally about the syntax which is packaged as part of ST, and so should be reported to [the Packages repository](https://github.com/sublimehq/Packages).

**Comment by r-stein** [comment]
Since this has been mentioned and discussed during the syntax rewrite reporting it there won't fix it.

**Comment by ig0774** [comment]
@r-stein: I simply meant to indicate that this is not an issue that's appropriate to discuss in the LaTeXTools repo since it concerns features we don't try to provide.
