### ISSUE TITLE
Script Builder: ps2pdf command fails, no pdf file is generated

### ISSUE THREAD

**Issue by yaronhe** [SublimeText/LaTeXTools#644]
other commonds are all OK

**Comment by ig0774** [comment]
Could you be a bit more specific about what you tried to do, what commands you ran with what arguments, etc.?

For example, setting up the script builder with these settings:

```json
"builder": "script",
"builder_settings": {
	"osx": {
		"script_commands": [
			"latex --synctex=1 --interaction=nonstopmode $file_name",
			"dvips -o $file_base_name.ps $file_base_name.dvi",
			"ps2pdf $file_base_name.ps"
		]
	}
}
```

Works for me on a really simple document...

**Comment by yaronhe** [comment]
The script is following:
"windows" : {
	"script_commands": [
            "latex -interaction=nonstopmode",
            "bibtex",
            "latex -interaction=nonstopmode",
            "latex -interaction=nonstopmode",
            "dvips -t letter",
            "ps2pdf"
        ]
}
The $file_base_name.ps file has been generated. But the last command "ps2pdf" failed. There is no pdf file.

the log for "ps2pdf" is also empty:
Invoking 'ps2pdf sig-alternate'... done.
Command results:

No errors

--------------------------------------------------------------------------------------------
Versions: Miktex 2.9 on windows 8.1
It is OK if I run "ps2pdf" command from cmd.exe

**Comment by ig0774** [comment]
You need to change the line that invokes `ps2pdf` to something like:

`ps2pdf $file_base_name.ps`

The script builder automatically appends `$file_base_name`  to any command that doesn't use any of the provided variables. This is because latex, bibtex, etc. tend to do the right thing when passed just the file name without extension ("sig-alternate" in your example). pdf2ps, however, needs the extension as well as the file name. The end result is that the command it tries to run with your setup is `ps2pdf sig-alternate`, which should fail even if you run it on the command line because your ps file is `sig-alternate.ps` not `sig-alternate`.

**Comment by yaronhe** [comment]
Thank you very much for your reply.
I have tried your advise. However, it does not work either.
And I also try on the other computer with the same environment (Miktex 2.9 + windows 8.1), the PDF file cannot be generated. So the error may not come from the installation of the Miktex.

**Comment by ig0774** [comment]
Have you set or changed the `texpath` setting either in your project settings or in your `LaTeXTools.sublime-settings`? I can duplicate what you're reporting (on Windows 7 admittedly) if I set the `texpath` to a value pointing to MiKTeX but nothing else...

**Comment by ig0774** [comment]
If the above is the case, please make sure your `texpath` setting contains `%PATH%`.

**Comment by yaronhe** [comment]
Thank you very muck. It works now after I add the %PATH% to the texpath
:)

**Comment by ig0774** [comment]
Great! Glad we got there in the end.
