### ISSUE TITLE
COULD NOT COMPILE! error when trying to comile on Linux

### ISSUE THREAD

**Issue by kuzmamar** [SublimeText/LaTeXTools#655]
I am not able to make this work. When I try to run compiling using Ctrl b from sublime I get:

> TraditionalBuilder: Invoking latexmk... 
> 
> COULD NOT COMPILE!
> 
> Attempted command:latexmk -cd -e -f -pdf -interaction=nonstopmode -synctex=1 min.tex
> Build engine: Traditional Builder

But running the command from terminal works fine.
The problem may be in file makePDF.py between 101 - 174. Some kind of exception is thrown.

**Comment by ig0774** [comment]
Is there any output in the Sublime console when this happens? You can get to the Sublime console either by pressing **ctrl + `** or the menu option **View | Console**.

 Normally this sort of thing is caused by a configuration issue e.g. where the path of your terminal doesn't match the path available to ST. Also what platform are you on? And which version of ST?

**Comment by kuzmamar** [comment]
Thanks @ig0774. The console output helped. But I am still confused. I have installed texlive on Linux Ubuntu 14.04 and in my .bashrc file i apended the installed folder "/usr/local/texlive/2015/bin/x86_64-linux" to the PATH variable. For some reason latextools could not find latexmk command. But then I tried to append the "/usr/local/texlive/2015/bin/x86_64-linux" to PATH variable in "texpath" under "linux" in user settings. This worked, which made me think under what user is the command executed? Certainly not me, because it didn't have my PATH variable available.
I am using sublime text 3.

**Comment by r-stein** [comment]
If you don't start ST from the shell, it won't read the environment variables. (The compile command is not run in a shell.)

I think variables set in the `~/.profile` are also access-able in ST.

**Comment by ig0774** [comment]
It's as @r-stein says: The problem is the environment visible to graphical applications differs somewhat from the environment visible on the login shell. Basically the environment graphical applications get derives from the display manager (on Ubuntu, usually `gdm`) which normally uses `/bin/sh` rather that `/bin/bash` to initialise its environment.

[The Ubuntu Wiki](https://help.ubuntu.com/community/EnvironmentVariables#Persistent_environment_variables) has a good run-down of the various places that you can put environment variables so they are visible to graphical programs, but basically , `~/.profile` is  the lowest common denominator read by both X and (almost all of) the various shell programs.

**Comment by kuzmamar** [comment]
Thanks @r-stein @ig0774 for clarifying that.

**Comment by YerongLi** [comment]
As @r-stein and @ig0774 pointed out, one good way to deal with this is to create a desktop icon as this:
```
[Desktop Entry]
Exec=sh -c "source /home/username/.bashrc;/home/username/local/sublime_text_3/sublime_text %F"
StartupNotify=true
Terminal=false
Type=Application
Icon=/home/username/local/sublime_text_3/Icon/128x128/sublime-text.png
Name[en_US]=Sublime Text 3
```
This will source  the **~/.bashrc** first and open Sublime Text later.
