### ISSUE TITLE
Biber solution 

### ISSUE THREAD

**Issue by grosdode** [SublimeText/LaTeXTools#660]
r-stein modify the Simple Builder to run with biber in this post #637. You can find the code, be careful and read the post from the 03. march 2016 because since the last update the original code doesn't work. 
Is it maybe possible to include this builder in Latextools ? (I often read this problem with biber)

**Comment by ig0774** [comment]
There's now a real sort of solution to this (assuming that `texify` for some reason doesn't properly handle `biber`), which is to use the new (in v3.8.0) `basic` builder. The `basic` builder is pretty much like the `simple` builder, but it handles more LaTeXTools features, such as engine selection, etc., and unlike the `simple` builder, will properly understand when to run `biber` instead of `bibtex`.
