### ISSUE TITLE
Verify focus before stealing it

### ISSUE THREAD

**Issue by vomout** [SublimeText/LaTeXTools#668]
On Linux, with 'keep_focus' set to 'true', LaTeXTools/SublimeText steals the focus when the build process is finished, even when it does not have the focus. On Mac this is not the case. After starting the build process, a simple typofix or so, I often immediately switch to a terminal to commit the changes in a (Mercurial) repository---or do something else in the terminal. Now, on Linux, the SublimeText window suddenly steals the focus, and the commit messages or whatever I'm typing go into my TeX file instead of the Terminal. On Mac this is not the case, the Terminal keeps the focus. Why is this so? I would expect 'keep_focus' set to 'true' to do nothing at all, unless a workaround is needed for a crappy PDF viewer. I know that Evince falls under that category for many other reasons, but does it also try to steal the focus when the file is updated?

**Comment by ig0774** [comment]
`keep_focus` means that LaTeXTools tries to keep the focus *on ST* after the build is complete, hence the behaviour you're describing. Set it to `false` and it should do what you want.

On Macs we are able to handle things differently because the `open` command has a switch to tell an application to start in the background. On Windows and Linux, there is no such switch and launching an application tends to entail it stealing the focus, hence our need to actively switch back to ST.

**Comment by vomout** [comment]
Ok, so it’s Evince’s fault? Or is there any way to not launch Evince when the pdf is updated? Setting keep_focus to false also does not work, as Evince stealing the focus is just as bad as SublimeText stealing it.

**Comment by r-stein** [comment]
Setting `forward_sync` to `false` should avoid the opening/focus of the pdf. You can still use `C-l, j` to manually jump to the pdf.

**Comment by ig0774** [comment]
In v3.12, I've switched things so that with Evince and Zathura, we shift focus as few times as possible if keep_focus is set to true. You can play with the delay between Evince being launched and focus being changed by modifying the keep_focus_delay settings in the platform-specific block (i.e. linux). If you really hate the focus switching hack, there is a new setting called disable_focus_hack which, if set to true, will disable LaTeXTools switching the focus altogether. Note, however, this is not the same as saying focus will never change as a result of LaTeXTools actions, since launching Evince tends to steal the focus.

This is probably as close as we're ever going to get to any version of "verifying focus".
