### ISSUE TITLE
user modified autocompletions

### ISSUE THREAD

**Issue by JimAmuro** [SublimeText/LaTeXTools#671]
Hi,
I love the autocompletion feature so much. I added and modified some autocompletions in the original file of latextools (like `LaTeX math.sublime-completions`). However, I don't know whether it shall survive package upgrades or not. So I am wondering if it is OK to modify the original file or there is a better way to add modified autocompletions. Thanks!

**Comment by ig0774** [comment]
Hi! The completion files have been pretty stable, so you *may* be OK to just modify those files. However, you're right that if they get updated, your changes will be lost. There are two obvious things you can do: 1) if you feel your changes would be useful for lots of people (e.g. they help support popular packages we don't yet support or commands, etc. missing) you could [submit a pull request](https://help.github.com/articles/using-pull-requests/) to have your changes integrated into LaTeXTools (we're always happy to have useful additions to the package). Or, 2) if your changes are specific to your preferences, etc. or otherwise might not be terribly useful to anyone else, you could [create your own completion file](http://docs.sublimetext.info/en/latest/reference/completions.html) in your User package, copying the scope from `LaTeX math.sublime-completions`. Sublime will take care of merging these completions with those defined in `LaTeX math.completions`. Hope that helps.

**Comment by JimAmuro** [comment]
Thank you very much! I'll take the second suggestion.
