### ISSUE TITLE
Change spell checking scope in latex files eg. don't spell check certain commands or comments

### ISSUE THREAD

**Issue by excetara2** [SublimeText/LaTeXTools#677]
I am assuming the LatexTools package sets this behavior for latex documents but for example I often write variable names in `\text{}` environments inside math `$...$` symbols. Is it possible to tell it to ignore certain environments like `\text{}` from spell checking. It already doesn't spellcheck in most the environments.

Also can you choose for it not to spell check latex comments. I didn't know if this was an easily modifiable setting as I didn't see it in the documentation. On a similar note, in coding syntaxes you'd probably only want to spell check comments.

**Comment by r-stein** [comment]
The settings for spell checking are not controlled by LaTeXTools, but be the `spelling_selector` setting in the user preferences.
Sublime Text usually uses the context of scope selectors for a lot of things and also to select where to spellcheck.

The scopes for the scope selectors are defined in the [syntax definitions](http://docs.sublimetext.info/en/latest/extensibility/syntaxdefs.html). Different selectors can be combined via `,` like an logical `or`, via `   ` *(space)* as an order preserving `and` and a `-` to exclude scopes.

The default setting is `"spelling_selector": "markup.raw, source string.quoted - punctuation - meta.preprocessor.c.include, source comment - source comment.block.preprocessor, -(source, constant, keyword, storage, support, variable, markup.underline.link, meta.tag)",`
If I understand you write, you want to use it in LaTeX but exclude comments and math modes. Hence we add `text.tex` to the excluded elements at the end and add `text.tex - (comment, string.other.math)` to the or-ed list. Hence **just paste this setting to your preferences**: `"spelling_selector": "markup.raw, source string.quoted - punctuation - meta.preprocessor.c.include, source comment - source comment.block.preprocessor, text.tex - (comment, string.other.math), -(text.tex, source, constant, keyword, storage, support, variable, markup.underline.link, meta.tag)",`

It is not possible to disable spellchecking in specific command, since it is bound to scopes and the command must have a unique scope defined in the syntax definition to do so. Since LaTeXTools does not have its own language definition we cannot do this.

PS.
- If you want to detect scopes I would recommend the [ScopeHunter](https://packagecontrol.io/packages/ScopeHunter) package.
- Since the way selectors work might not be to intuitive feel, free to add further questions to specify your problem.

**Comment by excetara2** [comment]
From ScopeHunter I have tried to write my own command but have failed a little so maybe you can help. The default command does not label things like `\textipa` or `\includegraphics' which now it labels those as spelling errors. I basically want what the default command does but just not spell check comments and math.

Also I am assuming from using ScopeHunter things inside some commands like `\includegraphics` that are just filenames don't have a specific meta reference so can't be turned off but that would be useful if possible. I think captions have the same scope as the `\includegraphics` commands and captions I would definitely want spell checked.

The closest I got was this:

```
	"spelling_selector": "markup.raw, source string.quoted - punctuation - meta.preprocessor.c.include, source comment - source comment.block.preprocessor, text.tex - (comment, string.other.math, meta.citation.latex), -(text.tex, source, constant, keyword, storage, support, variable, markup.underline.link, meta.tag)",
```

**Comment by excetara2** [comment]
Nevermind I think I got mostly what I want with this but still the comment on `\includegraphics` is valid :

```
	"spelling_selector": "markup.raw, source string.quoted - punctuation - meta.preprocessor.c.include, source comment - source comment.block.preprocessor, 
text.tex - (comment, string.other.math, meta.citation.latex, variable.parameter.function.latex, support.function.general.tex), 
-(text.tex, source, constant, keyword, storage, support, variable, markup.underline.link, meta.tag)",
```

**Comment by excetara2** [comment]
One more question since you seem to know a bit about the spell checker. Is it possible to set it to a minimum like three or four characters. Just curious. Thanks for all the help :+1:

**Comment by excetara2** [comment]
The other place I've noticed that it will spell check but not desired is the meta.braces but only directly after the command in that scope (ex. shown below). Any meta.braces further down  like in a `\multicolumn` command should be spell checked. I don't think the spell checker can be this specific?

`\begin{tabular}{ccp{6mm}p{6mm}p{6mm}p{6mm}p{6mm}p{6mm}}`

**Comment by r-stein** [comment]
To address all your questions:

- I agree that the way the ST spellchecker works is not optimal for LaTeX, because the scopes are not different for different commands. If you are really into it, you could change the syntax file to add additional scopes.
- I don't think its possible to only spellcheck with a minimum of 3 characters, but I know more about scopes and scope selectors than about the spellchecker.
- For the third I am not completely sure what behavior you want, but if you only want to spellcheck in meta groups with the nesting of 1 you can exclude nesting levels of 2 and above: `..., text.tex - (comment, ..., meta.group.braces meta.group.braces), ...`. If you want to only spellcheck a nesting levels of 2, but not of 1, then you can exclude nesting levels of 2 from the exclusions `..., text.tex - (comment, ..., meta.group.braces - meta.group.braces meta.group.braces), ...`

**Comment by excetara2** [comment]
- Okay I might have a look at syntax file a bit later and try adding some additional scopes. But it works pretty well with the additions from your help.
- Okay I can ask elsewhere but was just curious as I didn't think it would be easy to set
- Yes that got what I wanted:
`meta.data.environment.tabular.latex - meta.data.environment.tabular.latex meta.row.environment.tabular.latex`

- So basically the preamble isn't checked for spelling but all the cells are checked.
