### ISSUE TITLE
Forward jump in a project only jumps forward from the current file if in a sub-directory of the master file

### ISSUE THREAD

**Issue by excetara2** [SublimeText/LaTeXTools#707]
If you build your project and are in a sub-directory of the master file (aka chapter 1) then the forward sync will work for chapter 1 as well as any files in the same directory as the root. If you switch to another sub-directory (aka chapter 2) forward sync doesn't work properly and the only way is to re-build the project in which case the same thing happens again.

But in all cases reverse sync from Skim works properly. I am testing this on OsX.

**Comment by excetara2** [comment]
This weekend I'll upload to git hub a minimal working copy so you can see the structure and put the link here.

**Comment by ig0774** [comment]
Actually, I've managed to duplicate the issue and it looks like somewhere along the line I changed things to be accidentally passing a relative path instead of the absolute path. I'll try to figure out why I did that and get it fixed in the next release. Oddly, I still have no clue why a rebuild seemed to fix things. Sorry about that.

**Comment by excetara2** [comment]
Yes actually I am pretty sure it was working before the this fix as I thought I had the same configuration and I never noticed before it wasn't working although I was mainly working in individual files so not exactly sure. Okay I won't make a minimal example then.

Thanks!!

**Comment by excetara2** [comment]
Okay I've implemented the fix and all is good!
