### ISSUE TITLE
Bracket matching in math mode

### ISSUE THREAD

**Issue by mpvharmelen** [SublimeText/LaTeXTools#716]
Would it be possible to enable bracket matching in math mode?

Some information:
https://forum.sublimetext.com/t/bracket-matching-broken-in-latex-math-mode/6208

**Comment by ig0774** [comment]
The issue here has to do with the underlying syntax files, which are part of Sublime Text's [default packages](https://github.com/sublimehq/Packages) and not the LaTeXTools plugin, which is separate. That's not to say we couldn't create a custom syntax that would resolve this and perhaps some other issues. It's just to say that it's not as easy for us to do so as just "enabling" something.

There's a [proposal](https://github.com/sublimehq/Packages/issues/340) to update the LaTeX syntax files, which (if adopted) would resolve this issue on ST3 (only).

Probably the easiest solution is just use the [BracketHighlighter](https://packagecontrol.io/packages/BracketHighlighter) plugin, which has been updated since that forum post was written, and supports highlighting brackets in LaTeX math mode by default, and works on ST2 and ST3.

**Comment by KamphuisAlex** [comment]
BracketHighligher works for mee too. Also matches \begin{x} to \end{x}

**Comment by blizzardwj** [comment]
where is LaTeX syntax files? I cannot find it in [Rewrite the LaTeX syntax]https://github.com/sublimehq/Packages/issues/340

**Comment by r-stein** [comment]
@blizzardwj The pull request has been merged. So just download https://github.com/sublimehq/Packages and put the `LaTeX` folder in the packages folder (`Prefences >> Browse Packages...`).

**Comment by blizzardwj** [comment]
@r-stein thanks, I have got the idea.

**Comment by r-stein** [comment]
Since the new syntax definition is included in Beta Build `3124` I will close this issue.
