### ISSUE TITLE
Forward and backward search broken on Ubuntu 16.04

### ISSUE THREAD

**Issue by fph** [SublimeText/LaTeXTools#721]
I have a fresh Ubuntu 16.04 install (with Evince 3.18.2), and unfortunately forward and backward search does not work out-of-the-box anymore.

I have set the preference `"python2": "/usr/bin/python2"`, and checked that `"sublime": "subl"` is correct, but that doesn't help.

I am happy to perform more tests and help with the debugging if you tell me what to do.

**Comment by r-stein** [comment]
Have you tried to restart ST?

**Comment by ig0774** [comment]
Is forward sync (i.e. from Sublime to Evince) definitely broken as well as reverse sync (from Evince to Sublime). I ask because in 16.04 python-gobject was removed which the reverse sync depends on, but not the forward sync. If it's just the reverse sync, I have a fix in progress (it needs more testing). In the meantime, you could try installing the python-gobject package, which should get things working again.

**Comment by fph** [comment]
Yes, I have tried restarting ST. Neither forward (CTRL-L+J manually or automatically on compilation) nor reverse (CTRL+click on a point in the PDF on evince) work.

**Comment by fph** [comment]
Potentially useful information: when I type `CTRL-L+J` to invoke forward search, the following text appears in the ST console:
```
True False True
!TEX root =  '/path/to/my/tex/file'
Jump to:  65 338
<class '_latextools_evince_viewer.EvinceViewer'>
```
65, 338 are the line and column numbers corresponding to the current cursor location.

**Comment by fph** [comment]
I have fixed it! The trick was installing the `python-dbus` package. Without it, the two Python scripts named `evince/evince_backward_search` and `evince/evince_forward_search` (no extension, sic) fail. You may want to add this package as a dependency or document this.

**Comment by ig0774** [comment]
It looks like Ubuntu changed things so that only `python3-dbus` is required instead of `python-dbus` (the Python2 bindings), probably because the Gnome stuff has migrated to Python 3, whereas our scripts haven't (yet).

You're right we should document it, but hopefully, in the near future, we'll have things back to working out of the box.

**Comment by fph** [comment]
@ig0774 Thanks for the fix that you have already released, that was very quick! Unfortunately, though, I have to inform you that the scripts still do not work in Ubuntu 16.04 if python-dbus is not installed manually. This is because `python` still defaults to python2 there, and the very first line `import dbus` fails.

I can't think of a quick solution though; this seems a tricky issue. If one sets the shebang line to python3, then it doesn't work on systems in which it is not installed...

**Comment by ig0774** [comment]
@fph: it should work *provided* the `python2` or `python` setting is unset (which is the default). Basically I added a bit that runs `python -c "import dbus"` and, if that fails, `python3 -c "import dbus"` to find an interpreter with a compiled dubs module. However, if you set the setting to specify an interpreter, it uses the supplied value and doesn't do the check.

Shebangs don't really enter into the equation because we can't propagate the executable bit via git. All the scripts are run by explicitly invoking an interpreter.

**Comment by fph** [comment]
@ig0774 I confirm that you are correct -- forward/backward sync works with the `python2` setting unset and `python-dbus` uninstalled, which is the out-of-the-box state in Ubuntu 16.04. Thanks again!

**Comment by robjhyndman** [comment]
I'm using Ubuntu 16.04 with ST 3114. Forward sync works but reverse sync doesn't. I have python-dbus installed. How to fix it?

**Comment by fph** [comment]
What are the symptoms? Which pdf reader are you using? Did you set the `sublime` config variable correctly?

**Comment by ig0774** [comment]
@robjhyndman: The only outstanding issue I'm aware of is #710, which seems to involve `libsublime-imfix`. If you're using the same library, I don't have a solution just yet.

If not, you could try launching the `evince_sync` script from the terminal and see if any errors display. LaTeXTools effectively runs this:

```sh
cd ~/.config/sublime-text-3/Packages/LaTeXTools/evince
sh evince_sync <python> /opt/sublime_text/sublime_text "<full_path_to_pdf>.pdf"
```

`<python>` might be `python` or `python3` depending on the result of `python -c "import dbus"` and `python3 -c "import dbus"` or your `python2` setting (if it is set).

If reverse sync doesn't work when launching `evince_sync` from the terminal and there are no errors displayed in the terminal, the most likely cause is some issue with the URL encoding / decoding that takes place in the background. Reverse sync really only works when `evince_backward_search` thinks a file in Evince matches the file it was opened with. To troubleshoot that, it would be helpful to have the full path of the PDF file you're using.
