### ISSUE TITLE
feature request: pLaTeX 

### ISSUE THREAD

**Issue by speedcell4** [SublimeText/LaTeXTools#743]

**Comment by r-stein** [comment]
You should provide more information about your request. pLaTeX seems to be a LaTeX to html and pdf converter. If you want to use it as [build system](http://sublimetext.info/docs/en/reference/build_systems.html) you can easily create it for yourself. Otherwise you should write a description for your request.

**Comment by speedcell4** [comment]
@r-stein sorry. here are some more information about it.

pLaTeX is a special version of LaTeX which is designed for Japanese.

> LaTeX Error: This file needs format `pLaTeX2e' [\NeedsTeXFormat{pLaTeX2e}

error will be displayed if you us jarticle .cls, but replace the `DEFAULT_COMMAND_LATEXMK` in `traditionalBuilder.py` with the following code will solve this problem.

```python
DEFAULT_COMMAND_LATEXMK = ["latexmk", "-cd",
                    "-e", "$latex = 'platex -synctex=1 -src-specials -interaction=nonstopmode'",
                    "-e", "$biber = 'biber %O --bblencoding=utf8 -u -U --output_safechars %B'",
                    "-e", "$bibtex = 'pbibtex %O %B'",
                    "-e", "$makeindex = 'makeindex %O -o %D %S'",
                    "-e", "$dvipdf = 'dvipdfmx %O -o %D %S'",
                    "-e", "$pdf_mode = '3'",
                    "-e", "$pdf_update_method = '0'",
                    "-e", "$pdf_previewer = 'open -a preview.app'",
                    "-f", "-norc", "-gg", "-pdfdvi"]
```

**Comment by speedcell4** [comment]
But in that way, it will crash when turn back to use `% !TEX program = xelatex` pragma.

**Comment by ig0774** [comment]
@speedcell4: A couple of things:

1. It shouldn't crash, though it won't use `xelatex`. I'm not exactly sure why you would try to use that pragma, since it's not going to do anything any way. Are you using the latest release of LaTeXTools? An earlier version (prior to v3.5.0) was deeply tied to the exact format of `DEFAULT_COMMAND_LATEXMK` and would fail if you changed it.

1. Instead of *replacing* the command in `traditionalBuilder.py`, we actually have a setting that you can use to override the command run. In your builder settings block you could use something like this (I've eliminated a few unnecessary settings):

```json
"builder_settings": {
    "command": [
        "latexmk", "-cd",
         "-e", "$latex = 'platex -synctex=1 -src-specials -interaction=nonstopmode'",
         "-e", "$biber = 'biber %O --bblencoding=utf8 -u -U --output_safechars %B'",
         "-e", "$bibtex = 'pbibtex %O %B'",
         "-e", "$dvipdf = 'dvipdfmx %O -o %D %S'",
         "-f", "-norc", "-gg", "-pdfdvi"
    ]
}
```

1. If all else fails, have you tried the [script builder](https://github.com/SublimeText/LaTeXTools/blob/master/README.markdown#script-builder)? It essentially allows you to run any arbitrary sequence of commands.

**Comment by r-stein** [comment]
If I correctly understand your problem, you want sometimes use `platex` and sometimes `xelatex` and somehow easily change between those two? If yes: Do you use sublime projects to manage your documents or just write the files?

**Comment by speedcell4** [comment]
@r-stein yes, I often change between `platex` and `xelatex`.
and no project, just write .tex files.

**Comment by speedcell4** [comment]
@ig0774 sorry for my poor English, I did not make myself clear.

1. I just want a method to change between `platex` and `xelatex` easily. Yes, I am using the latest release of LaTeXTools. But the change I made for `DEFAULT_COMMAND_LATEXMK` works well when I use `platex`, but crashs when using `xelatex`.
2. I will try it.
3. too.

**Comment by r-stein** [comment]
@speedcell4 I don't know to integrate this into LaTeXTools in a generic way. However it would be easy to write a listener to change the builder in the settings of the view if the program is platex.

Open `Tools >>> Developer >>> new Plugin...` and paste:

``` py
import sublime_plugin
from LaTeXTools.getTeXRoot import get_tex_root
from LaTeXTools.latextools_utils import parse_tex_directives


class PlatexChangeListener(sublime_plugin.EventListener):
    def on_pre_save(self, view):
        # check we are in latex
        if not view.score_selector(0, "text.tex"):
            return
        # get the tex root
        tex_root = get_tex_root(view)
        if not tex_root:
            return

        # check the program is set to platex
        directive = parse_tex_directives(tex_root, only_for=["program"])
        if directive.get("program") != "platex":
            # erase previous setting (if change from platex to something else)
            view.settings().erase("builder_settings")
            return
        # set the build settings to platex
        view.settings().set("builder_settings", {
            "command": [
                "latexmk", "-cd",
                 "-e", "$latex = 'platex -synctex=1 -src-specials -interaction=nonstopmode'",
                 "-e", "$biber = 'biber %O --bblencoding=utf8 -u -U --output_safechars %B'",
                 "-e", "$bibtex = 'pbibtex %O %B'",
                 "-e", "$dvipdf = 'dvipdfmx %O -o %D %S'",
                 "-f", "-norc", "-gg", "-pdfdvi"
            ]
        })
```
This uses the insight how LaTeXTools work to change the build settings when you save the document. Then just use `% !TEX program = xelatex` and `% !TEX program = platex` in the root document.

**Comment by ig0774** [comment]
One option for how this could be implemented is to support sending options via the build system itself, something I've been thinking about with reference to the menu option in #255. Basically, we could set things up so that `make_pdf` and the `traditional` builder could understand a build system like this:

```json
{
	"target": "make_pdf",
	"selector": "text.tex.latex",

	"osx":
		{
			"file_regex": "^(...*?):([0-9]+): ([0-9]*)([^\\.]+)"
		},

	"windows":
		{
			"file_regex": "^((?:.:)?[^:\n\r]*):([0-9]+):?([0-9]+)?:? (.*)$"
		},

	"linux":
		{
			"file_regex": "^(...*?):([0-9]+): ([0-9]*)([^\\.]+)"
		},

        "command:"
        {
             "latexmk", "-cd",
             "-e", "$latex = 'platex -synctex=1 -src-specials -interaction=nonstopmode'",
             "-e", "$biber = 'biber %O --bblencoding=utf8 -u -U --output_safechars %B'",
             "-e", "$bibtex = 'pbibtex %O %B'",
             "-e", "$dvipdf = 'dvipdfmx %O -o %D %S'",
             "-f", "-norc", "-gg", "-pdfdvi"
        }
}
```

Saved as `pLaTeX.sublime-build`, this could allow switching between LaTeXTools standard build and this custom configuration using `C-Shift-B`, with a built-in selection panel, etc. This hasn't been implemented yet, it's just a thought on an approach.

**Comment by r-stein** [comment]
I think thats a nice idea to do it. I would also add the `builder` into the build system and take all necessary variables from the `*.build-system` if present, and from the settings otherwise.

**Comment by r-stein** [comment]
@ig0774 idea has been added in `v3.12.0` now you can use the suggested build system.
