### ISSUE TITLE
Simplify opening read-only settings

### ISSUE THREAD

**Issue by jrappen** [SublimeText/LaTeXTools#745]
### File

[`latextools_default_settings.py`](https://github.com/SublimeText/LaTeXTools/blob/master/latextools_default_settings.py)

### Changes

```diff
-        self.view = sublime.active_window().open_file(
-            os.path.join(
-                sublime.packages_path(),
-                "LaTeXTools",
-                "LaTeXTools.sublime-settings"
-            )
-        )
+        self.view = sublime.active_window().run_command('open_file', {'file': '${packages}/LaTeXTools/LaTeXTools.sublime-settings'})
```

### Improvements

* this change also works should LaTeXTools be converted into a `*.sublime-package`

**Comment by ig0774** [comment]
Thanks for the suggestion. Unfortunately, this doesn't quite work as the call to `open_file` returns a view while the call to `run_command` returns `None`. The upshot is that while this opens the default settings, it doesn't open it in read-only mode, which was the whole reason for implementing a separate command instead of just invoking the command from the menu file. We wanted to minimise the chances that people would mistakenly edit the default settings file and then lose their changes when the package updates (see #622 and #601).

**Comment by jrappen** [comment]
This change works (for zipped packages as well) for me:

```python
    def run(self):
        settings_read_only = sublime.load_resource('Packages/LaTeXTools/LaTeXTools.sublime-settings')
        v = sublime.active_window().new_file()
        v.run_command('append', {'characters': settings_read_only})
        v.set_name('LaTeXTools Settings - Default (read-only)')
        v.set_syntax_file('Packages/JavaScript/JSON.sublime-syntax')
        v.set_scratch(True)
        v.set_read_only(True)
```

afaik you could drop `__init__` and `set_view_readonly` from the class.

**Comment by r-stein** [comment]
Since we have a `.no-sublime-package` and rely on it not being zipped in several functionalities, I don't see a reason to add compatibility for this one.

**Comment by ig0774** [comment]
The other thing I'd note is that the `__init__` and `set_view_readonly` methods aren't necessary for ST3; they're there to properly support ST2.
