### ISSUE TITLE
\cite{} not recognizing bib files

### ISSUE THREAD

**Issue by sarinotsorry** [SublimeText/LaTeXTools#747]
I'm using Sublime Text to create LaTex documents via LaTexTools, and although it recognizes the .bib file when creating the bibliography at the end of the document, it does not recognize \cite{ref} when inserted into the text. I've redownloaded Sublime 2 twice, and tried to debug it myself, but can't seem to figure out the issue. The errors I get when I try to include a new citation are : "No bib files found" and "An error occurred while trying to run kpsewhich. TEXMF tree could not be accessed." The method I use to build is simple: just cmd+B. 

I've attached snapshots of the issue below. (On the PDF snapshot- the citation is denoted by a '?' instead of the citation). 

Disclaimer: I am new to both LaTex and Sublime, and am not a coder.

The folder where everything is collected is as follows: 
user/blakeley/0_ucsb/2016/Spring/geog266/finalproject/
and the files are as follows: blakeley_266_project.tex, Notesonreferences.bib, and I can see that it is generating the .aux, .latexmk, .fls, .log, .out, .pdf, .synctex.gz for the .tex file, as well as the .aux .bbl and .blg for the .bib file. 

Thanks in advance for any help you can give! 

<img width="584" alt="screen shot 2016-06-07 at 16 06 06" src="https://cloud.githubusercontent.com/assets/19808062/15877642/daf62166-2cc9-11e6-8a9d-deb0de3fd359.png">

<img width="272" alt="screen shot 2016-06-07 at 16 06 19" src="https://cloud.githubusercontent.com/assets/19808062/15877653/ed55fec6-2cc9-11e6-8e9f-50350c0275fa.png">

**Comment by r-stein** [comment]
How do you include you bib file?

**Comment by sarinotsorry** [comment]
The bib file is in the folder with the tex file. From what I understand, this should be enough? But I've also tried using the command "\iffalse \bibliography{Notesonreferences}" at the beginning of the tex file, no luck on getting it to recognize the bib file. I also have a command at the end of the bibliography section in my tex file that says \bibliography{references}, which seems to be working.

**Comment by r-stein** [comment]
You should have something like
``` latex
\bibliographystyle{plain}
\bibliography{Notesonreferences}
```
at the end of the document (but before `\end{document}`)

**Comment by sarinotsorry** [comment]
Yep, that's the last line before the \end{document}

**Comment by r-stein** [comment]
And the files are in the same folder?
You are on OSX with the default config?

**Comment by sarinotsorry** [comment]
Yep, the filers are in the same folder, and all is on default config (as far as I know, I don't think I've changed anything)

**Comment by ig0774** [comment]
To be very clear: does the last line say `\bibliography{references}` or `\bibliography{Notesonreferences}`? Bibfiles in the same folder will be detected, but not automatically. The `\bibliography` command tells bibtex which file to look for and must be included explicitly.

Do you get warnings about undefined references? The `\iffalse` command you referenced before will make `Notesonreferences` read by LaTeXTools, but not by LaTeX itself (this is one of the places where LaTeXTools handling of things differs somewhat from LaTeX's).

**Comment by sarinotsorry** [comment]
Sorry, that should have said \bibliography{Notesonreferences}, not {references}. The only errors I get are the " No bib files found" and "An error occurred while trying to run kpsewhich. TEXMF tree could not be accessed." when I try to input a new citation with \cite{}

**Comment by ig0774** [comment]
The "An error occurred while trying to run kpsewhich" is an error from the LaTeXTools plugin (probably indicating that you don't have kpsewhich installed or it isn't available on a path the plugin knows about). This is completely harmless in this case.

The "No bib files found" error is also from the plugin and indicates that it can't find the bibliography file referenced in what it thinks is the main directory. Bibliography files are assumed to be specified relative to the path of the *main tex file* (what LaTeXTools refers to as the "TEXroot"), because this is what LaTeX also assumes. The fact that you also get those **[?]** in the final document indicates that LaTeX itself cannot find the associated bibliography file.

Right now, there isn't enough information to work out what is wrong, but its possible that what LaTeXTools *thinks* is the main file is some file other than `blakeley_266_project.tex`, more specifically, a file in a different directory. This would happen if you have a `%!TEX root = ...` directive near the top of `blakeley_266_project.tex` or if the document is opened in a Sublime project that has a `TEXroot` setting (and if you used the `TEXroot` setting to specify a relative path, you should note that relative paths in project files are resolved *relative to the location of the `.sublime-project` file itself*).

You can check what LaTeXTools thinks the main file is by opening `blakeley_266_project.tex` in Sublime and running two commands from the Sublime Console (which you can access by selecting `View|Console` from the menu):

    from getTeXRoot import get_tex_root
    get_tex_root(sublime.active_window().active_view())

(you can just copy and paste those commands into the console one line at a time)

If this is anything other than the full path to `blakeley_266_project.tex`, that's the problem and you can resolve it by removing or modifying the `%!TEX root = ...` directive or the `TEXroot` setting (depending on which is set).

The only thing that's confounding this is that you do have a `.bbl` and `.blg` file, but those may be artefacts of a previous run that was at some point successful.

I apologise for the length of this; I hope its clear.

**Comment by sarinotsorry** [comment]
Thank you for the response! I appreciate the length, as this is not my area of expertise. It makes sense that the .tex path might be incorrect, so I tried the commands above that you suggested and got the results below: 

>>> from getTeXRoot import get_tex_root
>>> get_tex_root(sublime.active_window().active_view())
u'/Users/blakeley/0_ucsb/2016/Spring/geog266/finalproject/blakeley_266_project.tex'

which makes it look like the path is probably correct? 

However, I pulled the .bbl and the .blg documents out of the folder and reran the build to see if it would recreate those files, and the current build did not. So I suppose that the bib file is not actually running?

**Comment by r-stein** [comment]
Does the build log any errors?

**Comment by sarinotsorry** [comment]
I've uploaded the log for the final project here. It had a lot of warnings, but it says "No errors". One of the warnings does say "Latex Warning: There were undefined references."

[logforfinalproject.txt](https://github.com/SublimeText/LaTeXTools/files/307905/logforfinalproject.txt)

**Comment by ig0774** [comment]
You also have a `LaTeX Warning: Citation '.' on page 3 undefined on input line 201` warning which indicates that you have something like `\cite{.}` or maybe `\cite{somecitekey,.}` in your document. I also note that it seems to open a file called `d1.bbl` which seems to be an artefact of using `multibib` and may be why you don't have a whole range of `Citation... undefined` messages.

Would it be possible to post a minimum working example (see [here](http://meta.tex.stackexchange.com/a/3225) and [here](http://www.tex.ac.uk/FAQ-minxampl.html) for advice on how to make one) that demonstrates the same issue?

**Comment by sarinotsorry** [comment]
Thanks ig0774. I've uploaded a zip file that contains the following: 
example.tex and references.bib

The rest in the file is resulting from my making the pdf once. Strangely enough, it did make the .bbl and the .blg, although the citation itself is not working. 

[untitled folder.zip](https://github.com/SublimeText/LaTeXTools/files/312531/untitled.folder.zip)

**Comment by r-stein** [comment]
Your issue is based on the [multibbl](https://www.ctan.org/pkg/multibbl) package.

1. This changes all commands. Hence change `\cite{nicholson2009revised}` to `\cite{d1}{nicholson2009revised}`.
2. In addition the `bibtex` is not automatically run. Therefore open a terminal in the folder an run `bibtex d1`.

**Comment by sarinotsorry** [comment]
Wow, great, that worked! Thanks for helping me out and walking me through getting it to run. I really appreciate your patience with me and your advice, you saved my thesis proposal document!

**Comment by r-stein** [comment]
Glad to help, good luck with your thesis.
