### ISSUE TITLE
Evince and %!TEX root

### ISSUE THREAD

**Issue by Bradan** [SublimeText/LaTeXTools#796]
I'm using ST2, LaTeXTools and Evince on ArchLinux (64bit). I'm basically writing a book like document and every chapter is in a new file. I connect them via the `%!TEX root` method and it compiles the main file, but then it opens another instance of evince for every single chapter in which I issue the compile command, although all chapters are leading to the same main pdf file.

**Comment by ig0774** [comment]
This is a bizarre issue not because there may not be something wrong with what LaTeXTools is doing, but simply because [there's no way to get Evince to open multiple versions of the same document from the command line](https://bugzilla.gnome.org/show_bug.cgi?id=688636). Essentially, if you run `evince /path/to/myPDF.pdf` and that file is already open, Evince will just bring the window containing it to the foreground.

However, it *is* possible to open multiple copies of the same document *if* the path to the document is different, either because you have multiple copies of the same document in different directories or are using symlinks to point to the PDF or some such thing. LaTeXTools is a bit naïve about handling such things: we essentially just pass the supplied name to `evince`, so without a bit more information, its hard to guess what's happening. In particular, what does your directory structure for your document look like? Do your `%!TEX root` magic comments use relative or absolute paths?

**Comment by Bradan** [comment]
Thank you. You are right, there are symlinks. I will explain as shortly as I can how my directory structure looks like:

- Absolute path without symlink to the source directory:
  `/home/user/Dropbox/Uni/Master/project_thesis/project/svn/misc/thesis`
- Absolute path with symlink to the source directory:
  `/home/user/project_thesis/project/svn/misc/thesis`
- Structure inside the thesis folder:

        ├── bibtex
        │   └── thesis.bib
        ├── chapter1
        │   └── chapter1.tex
        ├── chapter2
        │   └── chapter2.tex
        ├── chapter3
        │   └── chapter3.tex
        .
        .
        .
        ├── thesis.tex

- Each of the chapterX.tex files start with `%!TEX root = ../thesis.tex` (so a relative path)
- The `thesis.tex` file and the chapter1 and 2 were opened over the symlink (`~/project_thesis/project/svn/misc/thesis/thesis.tex` can be read in the title bar of ST2)
- The remaining chapters were opened via the path without symlink!

That was the problem I think. I opened everything without symlink and now it just opens one instance of Evince. I remember that there is some canonical path routine in python. There should also be one that resolves symlinks. Can't we just convert the file path to it before launching the PDF viewer?

**Comment by ig0774** [comment]
Thanks for confirming that was the issue. There is a way to do this using `os.path.realpath()`. I'll try to get a patch together when I have some time.

**Comment by ig0774** [comment]
This is fixed in v3.10.0
