### ISSUE TITLE
Cannot type an opening brace after cite and friends

### ISSUE THREAD

**Issue by HughParsonage** [SublimeText/LaTeXTools#803]
Following the recent update, if I type `\footcite`, I am unable to type an adjacent `{`. I can type `}` or an opening brace elsewhere in the file, but if I hit the key, my cursor doesn't move.

The same problem occurs with `\textcite` and `\cite`, but not with other commands (`\textbf` etc). The LaTeX file compiles normally. 

It was working this morning if that helps.

**Comment by r-stein** [comment]
Do you see an error in the ST console (``ctrl+` ``)?

**Comment by HughParsonage** [comment]
No, no error.

**Comment by ig0774** [comment]
Do you get anything in the console at all? At the very least you should get the some messages about finding bibfiles... Can you type a `{` after `\ref` (assuming you use labels) or `\input` / `\include`? (Those last commands use the came auto-completion pathway).

**Comment by HughParsonage** [comment]
I get 

```
parseTeXlog: Parsing log file
parseTeXlog: FILE? Line:This is pdfTeX, Version 3.14159265-2.6-1.40.17 (MiKTeX 2.9) (preloaded format=pdflatex 2016.6.28)  7 AUG 2016 01:44
parseTeXlog: MATCHED
parseTeXlog: FILE? Line:entering extended mode
parseTeXlog: FILE? Line:**"C:/Users/Hugh Parsonage/Documents/sandbox/barebones.tex"
parseTeXlog: FILE? Line:("C:/Users/Hugh Parsonage/Documents/sandbox/barebones.tex"
parseTeXlog: MATCHED
parseTeXlog: FILE? Line:Babel <3.9r> and hyphenation patterns for 75 language(s) loaded.
parseTeXlog: FILE? Line:("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\base\article.cls"
parseTeXlog: MATCHED
parseTeXlog: FILE? Line:("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\base\size10.clo"
parseTeXlog: MATCHED
parseTeXlog: PERR [')' no files]
False True True
Jump to:  3 7
<class '_latextools_sumatra_viewer.SumatraViewer'>
```

I can type a `{` after `\input`  (and also get the dropdown menu), but not `\ref`.

**Comment by ig0774** [comment]
I'm having some problems reproducing this in my environment, so forgive me for the questions:

1) Are you on ST2 or ST3?
2) Are you using any packages besides LaTeXTools that might be interfering with the key binding or have you defined any custom keybindings for `{`? (The output of the `FindKeyConflicts: All Key Conflicts` command of the [FindKeyConflicts](https://packagecontrol.io/packages/FindKeyConflicts) package would be helpful, especially the `[{]` section.)
3) Do you get the same behaviour in the `barebones` file you posted in #802?

**Comment by HughParsonage** [comment]
1) ST3
2) Possibly AlignTab. Apart from that, I'm not using other packages.
3) Yes.

Weirdly it only reproduces on one of my computers.

**Comment by r-stein** [comment]
You can also open the ST console ``ctrl+` `` and write `sublime.log_commands(True)` to log the executed commands.

**Comment by HughParsonage** [comment]
```
>>> sublime.log_commands(True)
command: drag_select {"event": {"button": 1, "x": 379.5, "y": 464.5}}
command: latex_ref_cite {"insert_char": "{"}
command: latex_ref_cite {"insert_char": "{"}
command: drag_select {"event": {"button": 1, "x": 363.5, "y": 908.5}}
command: drag_select {"event": {"button": 1, "x": 213.5, "y": 855.5}}
command: drag_select {"event": {"button": 1, "x": 339.5, "y": 835.5}}
command: drag_select {"event": {"button": 1, "x": 335.5, "y": 887.5}}
command: drag_select {"event": {"button": 1, "x": 335.5, "y": 887.5}}
command: drag_select {"event": {"button": 1, "x": 335.5, "y": 887.5}}
command: drag_select {"event": {"button": 1, "x": 560.5, "y": 900.5}}
```

**Comment by ig0774** [comment]
Ok, at least it makes a certain kind of sense now. You've somehow ended up with a mixture of 3.10.x and 3.9.x. The dead give-away is that `latex_ref_cite` is being invoked and you still have definitions for `latex_fill_input` and `latex_fill_env`, all of which were removed from 3.10.x. Since it appears to favouring `latex_ref_cite` over `latex_fill_all`, this also explains the behaviour you're seeing. By itself, `latex_ref_cite` never created the drop-down menu, rather it ran either the citation or reference command depending on the context in which it was invoked. If neither of those commands exist, it would just silently do nothing, as it appears to be doing.

I'm completely baffled as to how your LaTeXTools install could've gotten into this state, but, fortunately, fixing it should be hard. Assuming you're using PackageControl, from the command palette (`C-shift-p`), select **Package Control: Remove Package** and then **LaTeXTools**. Once you get a message that's its been removed, open the command palette and select **Package Control: Install Package** and then choose **LaTeXTools**. It's probably a good idea to quit and restart Sublime after doing that.

**Comment by ig0774** [comment]
Oh... You've added something to the keybindings which changes things drastically.

**Comment by HughParsonage** [comment]
Possible reason: I tried to alter the syntax highlighting of `\ref` commands so that they were consistent. I used package resource viewer and altered the `LaTeX.sublime-syntax`. Would that have caused it? (If it did, it took a while for the error to occur.)

**Comment by ig0774** [comment]
No, that wouldn't have affected anything.

Looking at your keybindings—and I'm not sure why I didn't see this before, maybe they were cut-off in the email I was looking at?—you have a series of LaTeXTools-related keybindings in your User keybinding file (**Preferences|Key Bindings — User**). Get rid of those. They override the LaTeXTools-defined keybindings.

**Comment by HughParsonage** [comment]
Reinstalling the packages deleting the key-bindings solved the issue. Thanks for your help.

**Comment by ig0774** [comment]
Excellent!
