### ISSUE TITLE
cite auto completions not triggering

### ISSUE THREAD

**Issue by hsmao** [SublimeText/LaTeXTools#807]
The `\cite{}` autotrigger isn't bringing anything up. The `\ref{}` autotrigger works, and if the `\cite{xxx} `is input manually it shows up correctly in the final pdf. The console doesn't seem to react when `\cite{` is typed, but it does react when `\ref{` is typed. Do I have a corrupt install?

**Comment by r-stein** [comment]
Can you open the console an write `sublime.log_commands(True)` to validate, that the cite command is called?

**Comment by hsmao** [comment]
What is the expected result? Nothing happened (i.e. no output or messages)

**Comment by r-stein** [comment]
It should show `command: latex_fill_all {"completion_type": "cite", "insert_char": "{"}`, when you press `{` after `\cite`.

**Comment by hsmao** [comment]
So when `\cite{` is typed, the result is: `command: insert_snippet {"contents": "{$0}"}`

when `\ref{` is typed, the result is: 
`command: latex_fill_all {"completion_type": "ref", "insert_char": "{"}`
`TEX root: u'/Users/xxx/xxx.tex'`
`Searching file: u'/Users/xxx/xxx.tex'`

**Comment by r-stein** [comment]
Have you tried to restart ST to reload all plugins?

**Comment by hsmao** [comment]
...grumble face... 

Thanks for your help/patience, I wonder why that fixed it.

**Comment by r-stein** [comment]
There was an update on the ref completion today. The ref/cite/input-completions are loaded via an other module. I think the update intefered with the already loaded completions (reloaded files get an other module instance). Hence this problem should not come back soon.

@ig0774 I think this could be avoided by importing the fill all helper via `from LaTeXTools.latex_fill_all import FillAllHelper`. This seem to give the same singleton module even after refreshing a file.

**Comment by ig0774** [comment]
@r-stein: I don't *think* that's the issue. `LaTeXTools.latex_fill_all.FillAllHelper` is already a singleton instance. The actual class is defined in `latextools_utils/internal_types.py`, precisely to handle this sort of circumstance. That's why running something like:

```
> from LaTeXTools.latex_fill_all import FillAllHelper
> a = FillAllHelper
> from sublime_plugin import reload_plugin
> reload_plugin('LaTeXTools')
> from LaTeXTools.latex_fill_all import FillAllHelper
> b = FillAllHelper
> a is b
```

works (i.e. the final result is `True`) whereas doing the same sequence of commands, but using `LatexFillHelper` in place of `FillAllHelper` returns `False`. That said, I don't know what the underlying cause was.

**Comment by ig0774** [comment]
I think I've fixed the underlying issue here was actually related to the plugin stuff. The problem was that the plugin registry essentially gets reset when `latextools_plugin` gets reloaded.  The problem was that the fill_all_helpers (or at least some of them on ST3) were being registered in the old registry rather than the new registry and so weren't available when `on_query_context` is called so our new key bindings weren't matching, hence it defaults to ST's `{` binding (which is where the `insert_snippet` command was coming from.

I'll try to do something else in the future to make the plugin stuff less fragile... It really doesn't play very well with ST's module reloading, but in the meantime, hopefully this will fix things.
