### ISSUE TITLE
Automatic Complete after \begin

### ISSUE THREAD

**Issue by correia55** [SublimeText/LaTeXTools#817]
Using `\begin` and pressing Enter automatically creates the following code `\\begin{env} \end{env}` with two pointers, one at the end of each "env". The enhancement/correction would be to instead create `\begin{env} \end{env}`, without the extra "\".
After erasing "env", writing enumerate or itemize adds the code `item` between the two commands, instead of `\item`.

**Comment by r-stein** [comment]
That snippet is actually in the default LaTeX language package.
Since it is a snippet it is not easily possible to remove the leading `\`. We can do this in the cwl completion, because we create the completion programmically and remove the `\`, if it is already there.
Hence you need to just write `begin<enter>` or use a shortcut like `C-l, C-n` or `C-l, e` to create an environment.

The second thing seems to be a bug in the snippet and easy to fix. Just install [PackageResourceViewer](https://packagecontrol.io/packages/PackageResourceViewer) and open the file `LaTeX/Snippets/begin{}-end{}.sublime-snippet` in line 3 escape the backslashes, i.e. change the both `\item` to `\\item`.

**Comment by correia55** [comment]
Ok, I didn't know that.
I've fixed the second thing by following your instructions.

Thank you very much for your help.
I'll close the issue then.
