### ISSUE TITLE
Evince app icon and window steals alt-tab focus in GNOME 3.20

### ISSUE THREAD

**Issue by darthoctopus** [SublimeText/LaTeXTools#824]
In GNOME 3.20, the `evince_forward_search` script causes the Evince app icon to always appear at the front of the list when alt-tabbing, even when the window is not actually in focus. This is also true with the windows-only alt-tab extension enabled; the LaTeX document PDF window always appears as the first item on the list even when not in focus. Work around this by changing `evince/evince_forward_search` from

```        window.SyncView(
            tex_file,
            (line_number, 1),
            int(time.time()),
            dbus_interface="org.gnome.evince.Window"
```

to 

```        window.SyncView(
            tex_file,
            (line_number, 1),
            1,
            dbus_interface="org.gnome.evince.Window"
```

To be clear, this is a problem with either Evince or gnome-shell, and not LaTeXTools per se. Also, given gnome-shell's tendency to break API compatibility on a regular basis, I wouldn't be surprised if this were to cease to work next release, but this is fairly essential for me for now (because alt-tab is broken otherwise).

**Comment by ig0774** [comment]
Thanks for the really detailed write-up. It looks like the timestamp is passed to a call to [`gtk_window_present_with_time()`](https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-present-with-time) which may be tricking Gnome shell into thinking the application is raised even when it isn't. One thing I'm concerned about is does your proposed fix result in the proper ordering when the `keep_focus` setting is set to `false` (i.e., when Evince will always be given the focus)? Also, do things work with the value of `0` instead of `1`? (`0` is the constant for `GDK_CURRENT_TIME` and I'd expect it to give more consistent results in more scenarios.

**Comment by darthoctopus** [comment]
As far as I've tested:

1. the `keep_focus` setting seems to be respected — but one gets a notification that the window is ready (i.e. people with extensions like Steal My Focus would not be able to retain focus on the editor)
2. it also seems to work with the timestamp set to 0. In fact this was what the script looked like until May this year (probably because of a reference to a blog post from 2012 in a preceding comment — not sure how current that is now).
