### ISSUE TITLE
Idea: quick build shortcut for large documents preview

### ISSUE THREAD

**Issue by jdumas** [SublimeText/LaTeXTools#828]
Hi there,

When working with large documents (e.g. books or phd thesis), it notoriously takes forever to compile a document with latex.  Running latekmk can call pdflatex up to 5 times (!), when bibliography or indexes are involved.

However, when writing the actual document, most of the time one just wants a 'quick' preview of what one has written, so calling pdflatex in draftmode can be sufficient.

I was wondering if it is possible to have a second "build" shortcut/codepath in latextools, that would allow to call this "quick build preview" program (again, pdflatex in draftmode opposed to latexmk for example). For example ctrl+b can be "full build" (as before), and "ctrl+shift+b" can be the "quick build".

I don't know how things should be organized with e.g. synctex, or if a continuous build should run in the background and update the viewed document when typing is idle (and one is just reading the pdf). But I believe there is some room for improvement and it should be possible to make the experience more smooth for the user.

**Comment by r-stein** [comment]
I think this would in general be superseed by https://github.com/SublimeText/LaTeXTools/pull/775. Might be an idea to add a variant for draftmode, althrough you could easily add it on your own, when the PR is merged.

**Comment by ig0774** [comment]
Is what you're asking for having the `-draftmode` flag set or do you want something that sets the `draft` option on the `documentclass`? Those would be two very different implementations and two very different results (`-draftmode` doesn't write the final PDF). The third option, I suppose, is to just run `pdflatex` once which would be doable with #775. Actually, its doable today (using the script builder) but its a bit more annoying to turn on and off.

A continuous build is a good idea, but its not easy in ST right now, mostly because there is no way to detect (from a plugin) that ST is shutting down, which means that if we setup a continuous build, it would keep running after you exited ST or else we'd have to write at daemon process that runs the build and periodically checks that ST is still running.

Incidentally, although `latexmk` *can* run `pdflatex` up to 5 times, it *won't* (at least if you keep the `aux` and other files around). By default `latexmk` runs `pdflatex` *once* and *only* runs it additional times if the log file indicates that it should. The 5 time thing is an *upper limit* because some LaTeX documents can get into an infinite compilation loop.

**Comment by jdumas** [comment]
I think that's something up for a debate. Some people even like to have several entry points for their documents (e.g. a `draft.tex` and a `final.tex` file, which include the main document but define different options).

Right now my problematic is that I have a document which takes a long time to compile, and I want to preview changes I make without waiting too long (it can be including a new figure, editing text, etc.). If I start from `latexmk` scratch, my current document needs 4 calls to `pdflatex` to compile. Of course if I just update it and reuse previous `.aux` files, it's faster, but it can still call `pdflatex` 2 times (which I do not need just to preview my changes).

I think the solution brought up by #775 (just calling `pdflatex` once) is indeed a reasonable way to treat this problem.

As for point you mention about the continuous build, if you run it as a separate thread (without a fork or subprocess call), it would still close after ST exits right?

**Comment by r-stein** [comment]
I think @ig0774 meant, that we run `latexmk -pvc` for a continuous build. This would obviously require to call subprocess. However detecting idle time and run a "hidden" build (without forward sync, console, ...) after 30 sec idle would also be possible.

**Comment by r-stein** [comment]
Using https://github.com/SublimeText/LaTeXTools/pull/775 you can either create a build system with the content:
``` js
{
	"target": "make_pdf",
	"selector": "text.tex.latex",

	"osx": {
			"file_regex": "^(...*?):([0-9]+): ([0-9]*)([^\\.]+)"
	},

	"windows": {
			"file_regex": "^((?:.:)?[^:\n\r]*):([0-9]+):?([0-9]+)?:? (.*)$"
	},

	"linux": {
			"file_regex": "^(...*?):([0-9]+): ([0-9]*)([^\\.]+)"
	},

	"builder": "script",
	"script_commands": [
		"pdflatex -synctex=1 -interaction=nonstopmode"
	]
}
```

or a keybinding (with nearly the same content):
``` js
    {
        "keys": ["alt+b"],
        "command": "make_pdf",
        "args": {
            "osx": {
                    "file_regex": "^(...*?):([0-9]+): ([0-9]*)([^\\.]+)"
            },
            "windows": {
                    "file_regex": "^((?:.:)?[^:\n\r]*):([0-9]+):?([0-9]+)?:? (.*)$"
            },
            "linux": {
                    "file_regex": "^(...*?):([0-9]+): ([0-9]*)([^\\.]+)"
            },
            "builder": "script",
            "script_commands": [
                "pdflatex -synctex=1 -interaction=nonstopmode"
            ]
        },
        "context":
        [
            { "key": "selector", "operator": "equal", "operand": "text.tex.latex" }
        ]
    },
```

This will just run pdflatex once and you can obviously adapt the command with other flags

**Comment by r-stein** [comment]
Added in `v3.12.0`.
