### ISSUE TITLE
Locate all snippets/completions

### ISSUE THREAD

**Issue by diego898** [SublimeText/LaTeXTools#860]
In the [readme section on snippets](https://github.com/SublimeText/LaTeXTools#command-completion-snippets-etc) it says "by selecting **Tools|Snippets|LaTeX** and **Tools|Snippets|LaTeXTools** from the menu." but I don't see that in the menu anywhere? I only see two different sublime-snippet files in the latextools directory - one for figure (triggered by bfigure) and another for enviroment with no tab trigger. There is also a Latex math.sublime-completions. Are there any others?

**Comment by r-stein** [comment]
You can access the snippets via **Tools|Snippets...** or via the Command Palette (`ctrl+shift+p`) if you write "Snippet:". Since the information is outdated we will update the README.

The snippets and completions added by LaTeXTools are the 3 `.sublime-completions` files (`LaTeX`, `LaTeX math`, and `Beamer`) and 10 `.sublime-snippet` files. You may just search for the file type in the directory.
In addition the [LaTeX language package](https://github.com/sublimehq/Packages/tree/master/LaTeX/Snippets) contains a lot of snippets. If you want to access and edit those, I recommend to install [PackageResourceViewer](https://github.com/skuroda/PackageResourceViewer) to open and edit the snippets from `LaTeX/Snippets`.
