### ISSUE TITLE
Snippets weirdly creates two cursors!

### ISSUE THREAD

**Issue by IW242** [SublimeText/LaTeXTools#870]
When I type \beg, the code snippet popup box appears, "begin \begin{}...\end{}". 

If I push enter, then I get:

\\\begin{env}

\end{env}

with the "env" grayed out, and also note the double backslash. Then if I begin to type "equation", it will type over the grey "env" areas using two cursors. So far so good (except for the double backslash!). But then when the popup box comes for "equation", and I push enter, then it duplicates the whole thing again, so now I have TWO \begin...\end environments, and FOUR cursors, and its all screwed up. What is going on? Working on a Mac with the latest version of LaTeXTools.

**Comment by ig0774** [comment]
These are the result of two separate snippets located in the LaTeX built in package. Unfortunately, from this plugin, there is no way of disabling them. The multiple cursors, incidentally, are a feature, allowing you to edit both ends of the `\begin{}...\end{}` block at once. The problem is that the **Equation** snippet isn't to insert the *word* "equation", it insert the whole

```latex
\begin{equation}

\end{equation}
```

If you just want an equation environment, probably the easiest thing to do is to just type `eq` and press tab which will give you the above text.

**Comment by r-stein** [comment]
The first snippet replaces `begin` (not `\begin`) with
``` tex
\begin{env|}
\end{env|}
```
with two selections to change the begin and end environment command at the same time.
Then you use a snippet to replace `eq` with
``` tex
\begin{equation}
|
\end{equation}
```
which is substituted for each cursor.

As @ig0774 said you should directly use the equation snippet. However for a general solution you can install [LaTeX-cwl](https://packagecontrol.io/packages/LaTeX-cwl), which will add cwl completions with LaTeXTools to provide environment name completions. Then you can create the environment via `begin<tab>` or `C-l, C-n` and get the possible environment names in the completion popup.

**Comment by IW242** [comment]
Ok, thank you gentlemen.
