### ISSUE TITLE
How to remove the warning and error bar?

### ISSUE THREAD

**Issue by Robert-Lu** [SublimeText/LaTeXTools#874]
![image](https://cloud.githubusercontent.com/assets/12983183/19517965/e4cbab26-9636-11e6-9f1f-198632bf636c.png)

Like that.
Actually I am not sure it is cause by LaTeXTools, but I only see these bars in here.
And I tried some time to find way to remove it, but fail.
Thanks in advance for your help~ 
🙇

**Comment by r-stein** [comment]
They are added to the normal builds, and separatly to LaTeXTools (because it has a more complicated build system). If you only want to disable it for LaTeXTools change the [`show_error_phantoms`](https://github.com/SublimeText/LaTeXTools/blob/v3.11.2/LaTeXTools.sublime-settings#L357) setting to `"none"` in the LaTeXTools settings.
If you want to disable it globaly set `show_errors_inline` to `false` in your user settings.

**Comment by Robert-Lu** [comment]
Very thanks.
I finally set it to `"show_error_phantoms": "errors"` because I just do not want the warnings to show.
