### ISSUE TITLE
Replacement of characters in \label{}

### ISSUE THREAD

**Issue by sonOfRa** [SublimeText/LaTeXTools#881]
When generating a new chapter/section/subsection etc., a label is automatically generated with the same text, except the text is all lowercase and spaces are replaced by underscores. This is usually enough to generate a valid label, but if the section name contains german Umlauts like äöüÄÖÜß, these are inserted verbatim into the label, which produces an invalid label. If possible, these should be replaced with aouAOUss, respectively.

Since this may also be a problem for other, non-german languages, maybe a solution like https://pypi.python.org/pypi/Unidecode might be helpful since this translation isn't really trivial for a lot of more complicated characters.

**Comment by r-stein** [comment]
You are refering to [section snippet](https://github.com/sublimehq/Packages/blob/master/LaTeX/Snippets/section-..-(section).sublime-snippet)?

**Comment by sonOfRa** [comment]
Yes, that and the respective versions for subsection, chapter etc.

**Comment by ig0774** [comment]
Two things here:

1. Those snippets are actually bundled with ST's LaTeX package rather than LaTeXTools, which means that we can't (from here) get rid of them entirely.

1. It's probably possible to do something a bit different with the label generation, but it's not a straight-forward task. Basically, there's no API hooks directly into the label substitution part so we'd have to add something that listens to every key-stroke and makes the appropriate substitution when necessary. I'm a bit hesitant to add something like that mostly because it seems liable to add a fair bit of processing to edit LaTeX documents and I think most of the reason people use ST for LaTeX editing is to have something snappy and light-weight. Still, we can keep this for consideration.

**Comment by r-stein** [comment]
This should be soly done by the field replacements of snippets. Hooking into it will break autocompletion and more.
However could add `\label{` to fill all helper with the replacement suggestions.
