### ISSUE TITLE
Cannot compile within Sublime 3 at Windows 10

### ISSUE THREAD

**Issue by znss1989** [SublimeText/LaTeXTools#882]
I basically followed guides here to run texlive 2016 within Sublime 3. But always reports error message like this: 

> SimpleBuilder: pdflatex run 1; 
> 
> COULD NOT COMPILE!
> 
> Attempted command:pdflatex -interaction=nonstopmode -synctex=1 testtesttest
> Build engine: Simple Builder

My user setting for LaTeXTools package modified like this:

```
	"windows": {
		// Path used when invoking tex & friends; "" is fine for MiKTeX
		// For TeXlive 2011 (or other years) use
		// "texpath" : "C:\\texlive\\2011\\bin\\win32;$PATH",
		"texpath" : "C:\\texlive\\bin\\win32;$PATH",
		// TeX distro: "miktex" or "texlive"
		"distro" : "texlive",
		// Command to invoke Sumatra. If blank, "SumatraPDF.exe" is used (it has to be on your PATH)
		"sumatra": "D:\\Program Files\\SumatraPDF;$PATH",
		// Command to invoke Sublime Text. Used if the keep_focus toggle is true.
		// If blank, "subl.exe" or "sublime_text.exe" will be used.
		"sublime_executable": "D:\\Program Files\\Sublime Text 3\\sublime_text.exe;$PATH",
		// how long (in seconds) to wait after the jump_to_pdf command completes
		// before switching focus back to Sublime Text. This may need to be
		// adjusted depending on your machine and configuration.
		"keep_focus_delay": 0.5
	},
```

Any more specific information needed, please tell me.

**Comment by r-stein** [comment]
Does it show any errors, if you open the ST console ``ctrl+` ``?

**Comment by ig0774** [comment]
This is incidental, but you're `sumatra` and `sublime_executable` settings aren't correct. They should be `D:\\Program Files\\SumatraPDF\SumatraPDF.exe` and `D:\\Program Files\\Sublime Text 3\\sublime_text.exe` respectively. Ideally, however, you shouldn't need to configure them at all.

More to the point, can you double-check that your TeXLive installation is really setup to use `C:\texlive\bin`. Usually TeXLive's binaries are in `C:\texlive\<year>\bin`, i.e., `C:\texlive\2016\bin`, since you installed TeXLive 2016. Being unable to find the binaries would be an obvious cause for that issue.

Finally, for a range of reasons, I'd use the `basic` builder instead of the `simple` builder.

**Comment by znss1989** [comment]
@r-stein It seems somehow working now. 

Now the console shows

> <class '_latextools_simpleBuilder.SimpleBuilder'>
> 2
> Welcome to thread Thread-4
> ['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'jrnl_fggf_2']
> Finished normally
> 0
> False True True
> Jump to:  7 2
> <class '_latextools_sumatra_viewer.SumatraViewer'>



@ig0774 Yes that my TeXLive installation should not be `C:\texlive\bin` but  `C:\texlive\2016\bin\win32` now. I also use the basic builder now. For `sumatra` and `sublime`, do you mean that I should not include the `;$PATH`?



Thank you both for helping.

**Comment by r-stein** [comment]
You should not include the path for the executables, because we need those commands to call the programms.

**Comment by znss1989** [comment]
I see, so these places should have executables, right?

**Comment by ig0774** [comment]
Yes, just the executables. But, as I said, they should both be unnecessary.

**Comment by znss1989** [comment]
Got it, thanks.
