### ISSUE TITLE
Autocomplete gives extra "\"

### ISSUE THREAD

**Issue by yzlnew** [SublimeText/LaTeXTools#888]
![1](https://cloud.githubusercontent.com/assets/4904877/19852896/06f3578a-9fa1-11e6-8de0-6e997ae534fe.gif)
On Windows 10 64bit / SublimeText 3 build 3126
Having this issue since the latest update of LaTeXTools.

**Comment by r-stein** [comment]
That's weird, because we explicitly strip the leading `\` only of if we insert a snippet (something with {...}), because we endet up with on `item` instead of `\item` for that case.

You can just replace `(c[0], c[1][1:]) if _is_snippet(c) else c` by `(c[0], c[1][1:])` [here](https://github.com/SublimeText/LaTeXTools/blob/v3.12.0/latex_cwl_completions.py#L316).

**Comment by yzlnew** [comment]
Thanks for saving my day. 
Works fine now.

**Comment by r-stein** [comment]
I reopen this, because it is a general issue and we still need to fix it.

**Comment by skulumani** [comment]
I have a similar issue to this for auto-filling images

Try the following

* Type `\includegraphics[width=\textwidth]{}`
* Click within the braces and hit `Ctrl-l, Ctrl-f` and pick an image.
* Notice that you're now left with an additional brace

This usually happens when I need to modify an image and simply delete the contents of the brace rather than starting over. 

I think a similar solution as the `\` fix is required.

Thanks for the great plugin!

**Comment by ig0774** [comment]
@skulumani: That probably should be its own issue; however, I can't really reproduce it here:

![gif showing C-l,C-f working as expected with \includegraphics](https://cloud.githubusercontent.com/assets/212893/19923780/fac2ee80-a0e0-11e6-9995-8761f4dc2cdb.gif)

Is it possible you have a `C-l,C-f` binding in your User keybindings?

**Comment by skulumani** [comment]
Thanks for taking a look. Let me try to reproduce and take some screen
shots today
