### ISSUE TITLE
documentclass auto-completion

### ISSUE THREAD

**Issue by hguandl** [SublimeText/LaTeXTools#948]
Just like the picture below, there are selections of document classes. I've installed ctex for Chinese support and want to use ctexart as the documentclass, but I cannot find it among the selections. Can I add more selections? 
![qq20161120-0](https://cloud.githubusercontent.com/assets/10684225/20457969/def4e1fe-aed2-11e6-8758-29124162a90c.png)

**Comment by r-stein** [comment]
Try to press open the command palette (ctrl+shift+p) and run the the command "LaTeXTools: Build cache of LaTeX packages".

**Comment by shouwei** [comment]
Personally speaking, I strongly recommend that you should not rely on this feature because it would cause several unexpected behaviors. You can refer to this link: [https://github.com/SublimeText/LaTeXTools/issues/957](url)

In particular, document class is not used so often, then you can just type these letters and don't  need to depend on the IntelliSense.

**Comment by r-stein** [comment]
Please be aware, that the documentclasses are parsed from the available class files and hence you should find your class if the cache is up to date.
In contrast the environment names are parsed from cwl files, which contains a discription for each package. Hence we can only provide the environments of packages, whose cwl files exists. In addition not all cwl files are complete.
However you can also add you own cwl files at `Packages/User/cwl`.
