### ISSUE TITLE
question about math preview

### ISSUE THREAD

**Issue by shouwei** [SublimeText/LaTeXTools#976]
Hi,

I started to try the "math preview" feature from this morning and have two questions.

1st, is that possible to speed up the showing procedure? For example, after typing one math symbol ($\leftarrow$), the preview picture shows up after around 1 second on my laptop. I tried several symbols and found that the current strategy should be like this: a preview image would be generated only a COMPLETE symbol has been typed. So we have to wait 1 second for the image generation. I am considering an alternative greedy strategy that an image will be generated as soon as it can be deduced. Taking the letter $\alpha$ as an example, after we get letters "alp" with math environment, the complete form must be (or w.h.p) $\alpha$, and the generation time could save up to 60%.

2nd, can we customize a set of pictures as the preview picture? If yes, would you please show me one example or a guide. I have a very nice set of symbols and want to use them in the math preview. Please refer to the attachment (all of these image are png format).

Thank you!
![sym_1](https://cloud.githubusercontent.com/assets/4194670/20865772/aa8498e8-ba1b-11e6-996b-7bdd799a3b1d.png)
![sym_11](https://cloud.githubusercontent.com/assets/4194670/20865776/b0a7678c-ba1b-11e6-99be-4bf8e1ba0659.png)
![sym_130](https://cloud.githubusercontent.com/assets/4194670/20865777/b66e5e00-ba1b-11e6-9a4a-1aada646ee50.png)
![sym_137](https://cloud.githubusercontent.com/assets/4194670/20865781/cf2f3c52-ba1b-11e6-86cd-cb8f90935cde.png)

**Comment by r-stein** [comment]
1. The current strategy is to create the preview after you have stopped typing and the maximal duration between 2 keystrokes is set to 600 ms. I.e. the generation will be started 600 ms after your last keystroke. This number is kinda random based on what worked best for me.
  We cannot only generate the image for completed symbols just because we don't know whether a symbol is complete or not. The whole image generation process is done via pdflatex and ghostscript.
  Therefore using your strategy is not possible.
2. The preview is generated by compiling a template document. You can set the used packages and defined commands for that document in the [settings](https://github.com/SublimeText/LaTeXTools/blob/v3.12.11/LaTeXTools.sublime-settings#L125). Hence you can costumize it as fas as you can costumize your latex program.

**Comment by shouwei** [comment]
1. is the 600 ms delay configurable? I prefer a faster generation.
2. Greek letters and most symbols are included in amsmath (and some other) package, but somehow what I want is to replace the png pictures, for example, replace the current $\alpha$ preview image with the picture in my post.

**Comment by ig0774** [comment]
Re 2: At least for me, the default settings generate exactly the glyphs you want, albeit scaled down to a relatively small size:

Enlarged:
<img width="310" alt="\alpha\Theta\biguplus\Leftrightarrow large" src="https://cloud.githubusercontent.com/assets/212893/20866096/bb07ba92-ba1b-11e6-8c0a-b4e9ebd1c6cc.png">

Normal rendering:
<img width="84" alt="\alpha\Theta\biguplus\Leftrightarrow normal" src="https://cloud.githubusercontent.com/assets/212893/20866101/ea3fcbba-ba1b-11e6-9a22-e29566268861.png">

In general, if you want to replace the symbols with other symbols you need to adjust the settings as @r-stein indicated. If you're just looking to increase the *size* of the image, you can try upping the [`preview_math_density` setting](https://github.com/SublimeText/LaTeXTools/blob/v3.12.11/LaTeXTools.sublime-settings#L145) (my enlarged image was generated with this set to `1200`). That said, this will increase the size of all the generated previews.

**Comment by shouwei** [comment]
@ig0774 

Perfect solution! The 2nd problem is done. Thank you!

Then the left issue would be how to reduce the generation time.

**Comment by r-stein** [comment]
The delay until the job ist started is not configurable, because it runs on the main thread on every modification and we don't want to slow down ST. In addition to conversion to create the preview also requires some time. So reducing this from 600 to 300 would not help too much in the delay until the preview image is ready.

**Comment by shouwei** [comment]
thanks all!
