### ISSUE TITLE
Preview mode for math live preview: "all" is impractical for inline math $$

### ISSUE THREAD

**Issue by phdoerfler** [SublimeText/LaTeXTools#997]
I would like to suggest an additional setting so one can have `"preview_math_mode"` set to `"all"` but only for `displaymath` (and similar) environments. Right now setting this to `"all"` is impractical when using `$$` as can be seen on this screenshot:

![bildschirmfoto 2017-01-08 um 20 24 59](https://cloud.githubusercontent.com/assets/163428/21752878/a87c13ba-d5e0-11e6-8a3b-1fb60a06fa4d.png)

Instead I would like to see an additional value that behaves for `displaymath` equations as if it was set to `"all"` but for inline ones as if it was set to `"selected"`.
Alternatively having the inline ones use up less space (vertically) so they fit in the same line might also work well.

**Comment by diego898** [comment]
This is a great idea! I'm currently getting around this with a set of disable/enable keyboard shortcuts

**Comment by garylavayou** [comment]
Currently, I have a problem about the preview mode of _LaTeXTools_. 
I have set the preview mode to `all` in the configuration file. However, only the `displaymath `equations have preview, while the `inlinemath `has no preview, as shown in the following figure

> ![image](https://user-images.githubusercontent.com/25133690/29697437-c9add212-8981-11e7-9e08-0c2c8f3fb513.png)

Although this problem is similar to the feature is requested by @phdoerfler, and I also think its useful, how could I enable the `all `mode? I doubt if I have some wrong configures leading to this problem.

**Comment by r-stein** [comment]
@garylavayou Just change the [`preview_math_scope`](https://github.com/SublimeText/LaTeXTools/blob/st3-3.14.1/LaTeXTools.sublime-settings#L107) setting to `text.tex.latex meta.environment.math` .
