### ISSUE TITLE
Math preview too large

### ISSUE THREAD

**Issue by tob1as** [SublimeText/LaTeXTools#999]
The font size of the math preview is very very big. See the screenshot, I guess this is not how it's intended to be. I am using the Linux version of Sublime Text 3. Does this occur for anybody else? I have not changed any settings.

It's a nice feature though!

EDIT: setting _hires = False in preview_math.py fixed the issue for me.

![screenshot_2017-01-09_12-46-33](https://cloud.githubusercontent.com/assets/25006212/21765530/b290e7a2-d669-11e6-9829-f74ecb42054c.png)

**Comment by ig0774** [comment]
Try lowering the `preview_math_density` setting. By default it should be either `150` with a `preview_math_scale_quotient` of `1` or `300` with a `preview_math_scale_quotient` of `2` (depending on when you started using it). Larger densities without changing the corresponding scale quotient results in larger images.

**Comment by r-stein** [comment]
The `-dDownScaleFactor=` option does not seem to be supported with each ghostscript. I have the same problem and the images are 8 times the size they should be. In addition there is a typo in the settings name https://github.com/SublimeText/LaTeXTools/commit/f0404949792dd07908cfeb615f10302996d70e28.

Not sure what is the best to handle this.

**Comment by ig0774** [comment]
@r-stein: Yes, you're right. It looks like `-dDownScaleFactor` was only added to the `pngalpha` in 9.14 (AFAIK the current versions of MiKTeX and TeXLive on Windows use 9.20).

I see a two options:
1. We **could** get a little further by using the `png16m` device and specifying the background colour (`png16m` is full 24-bit, but no alpha channel). That would allow us to support GS 9.10 or newer.
1. We could cache the GS version when we find the executable and treat `hires` as being `False` if it's a version before 9.14 (GS version numbering has been very consistent since 5.xx at least).

We could even combine both of those.

Sorry I didn't look into support for the `-dDownScaleFactor` option more thoroughly before releasing that change... I was more concerned that it seemed to work with the pre-installed versions of MiKTeX and TeXLive as well as a normal GS install.

**Comment by Quirinekrol** [comment]
Did anyone find a work-around solution? Please share, because the preview feature is extremely nice, but not functional in this state.

**Comment by r-stein** [comment]
Just set [preview_math_scale_quotient](https://github.com/SublimeText/LaTeXTools/blob/v3.12.15/LaTeXTools.sublime-settings#L148) to `8` (by adding `"preview_math_scale_quotient": 8,` to your LaTeXTools - User settings).

**Comment by r-stein** [comment]
I have released a new version to fix this. Just remove `preview_math_scale_quotient` after the update.
